openapi: 3.0.3
info:
  title: Banking - Assets
  version: 1.0.0
  description: API to handle banking assets operations and management
  contact:
    name: API Support
    url: https://developers.pismo.io/support
  license:
    name: Copyright Pismo
servers:
  - url: https://sandbox.pismolabs.io/assets-accrual
    description: Sandbox API server for testing
  - url: https://sandbox.pismolabs.io/assets-accrual
    description: Sandbox API for oauth2
  - url: https://api.pismolabs.io/assets-accrual
    description: API server for production
security:
  - BearerAuth: []
tags:
  - name: Assets
    description: Asset endpoints
  - name: Quotas
    description: Quota endpoints
components:
  parameters:
    AssetID:
      name: asset_id
      in: path
      description: >
        Client assigned asset ID. Must consist of the characters
        [a-z,A-Z,0-9,-,:] with a range from 1 to 128.
      required: true
      schema:
        type: string
      example: '2345'
    BeginDate:
      name: beginDate
      in: query
      required: false
      description: Date asset was issued
      schema:
        type: string
        format: date
      example: '2023-01-10'
    CorrelationID:
      in: header
      name: x-cid
      schema:
        type: string
      description: >
        The Correlation IDentifier field is used to link related API requests
        and events.  The x-cid can help the Pismo engineering team track
        everything related to a call. You can find the x-cid field in the
        response header from an API endpoint call.


        If this field isn't passed, one is automatically generated.
      example: 5bb05174-4e80-11ea-b77f-2e728ce88125
    EndDate:
      name: endDate
      in: query
      description: Date asset was redeemed, format = yyyy-mm-dd.
      schema:
        type: string
        format: date
      example: '2023-01-10'
    ExternalId:
      name: externalId
      in: query
      required: true
      description: >-
        Client-provided external asset ID. No longer than 128 alphanumeric
        characters.
      schema:
        type: string
      example: '3456'
    IssuerID:
      name: issuer_id
      in: path
      required: true
      description: >-
        Issuer ID. For more information, refer to [issuer identification
        number](https://www.investopedia.com/terms/i/issuer-identification-number-iin.asp)
      schema:
        type: string
      example: '24'
    Page:
      name: page
      in: query
      required: true
      description: Page number, default is 1.
      schema:
        type: integer
        format: int32
      example: 1
    PerPage:
      name: perPage
      in: query
      required: true
      description: Number of items per page, default is 10.
      schema:
        type: integer
        format: int32
      example: 10
    QuotaID:
      name: quota_id
      in: path
      required: true
      description: Quota ID
      schema:
        type: string
      example: '3456'
  schemas:
    UnitsAvailable:
      type: number
      format: integer
      description: total units available after redemption operation
      example: 3000
    AccrualFrequency:
      type: string
      description: |
        Accrual frequency:
        * `daily` — Accrual for assets daily
        * `monthly` — Accrual for assets monthly
      enum:
        - daily
        - monthly
      example: daily
    AccumDailyRate:
      type: number
      format: double
      description: Accumulative daily rate
      example: 1.2
    AdditionalData:
      title: AdditionalData
      example:
        early_redemption_attributes:
          - date: '2021-02-01'
            interest_rate: 1.09
            floating_rate: 1.18
          - date: '2021-03-01'
            interest_rate: 100000000000001.1
            floating_rate: 1.15
      type: object
      properties:
        early_redemption_attributes:
          type: array
          items:
            $ref: '#/components/schemas/EarlyRedemptionAttribute'
    Asset:
      type: object
      example:
        asset_id: 2334c547-c3f6-4d83-a933-16a3835a0065
        asset_type: cdb
        issuer_id: '12345678'
        registration_mode: single
        issuing_date: '2021-01-10'
        maturity_date: '2022-03-10'
        created_at: '2023-03-30T12:26:41'
        updated_at: '2023-03-30T12:26:41'
        issued_units: 1000
        unit_value: 9.99
        customer_type: natural
        customer_name: Helen Wheels
        document_number: '12345678901'
        deposit_number: 998-878-090
        early_redemption_terms: market
        index_type: di
        index_rate: 1
        status: ACTIVE
        currency: '986'
        interest_rate: 0.1
        additional_data:
          early_redemption_attributes:
            - date: '2021-05-20'
              interest_rate: 0.04
              floating_rate: 1.12345678
            - date: '2021-12-01'
              interest_rate: 1.12345678
              floating_rate: 1.12345678
        accrual_frequency: daily
      properties:
        asset_id:
          $ref: '#/components/schemas/AssetID'
        asset_type:
          $ref: '#/components/schemas/AssetType'
        registration_mode:
          $ref: '#/components/schemas/RegistrationMode'
        issuing_date:
          $ref: '#/components/schemas/IssuingDate'
        maturity_date:
          $ref: '#/components/schemas/MaturityDate'
        issued_units:
          $ref: '#/components/schemas/IssuedUnits'
        unit_value:
          $ref: '#/components/schemas/UnitValue'
        index_type:
          $ref: '#/components/schemas/IndexType'
        index_rate:
          $ref: '#/components/schemas/IndexRate'
        currency:
          $ref: '#/components/schemas/Currency'
        status:
          $ref: '#/components/schemas/Status'
        issuer_id:
          $ref: '#/components/schemas/IssuerID'
        created_at:
          $ref: '#/components/schemas/CreatedAt'
        updated_at:
          $ref: '#/components/schemas/UpdatedAt'
        interest_rate:
          $ref: '#/components/schemas/InterestRate'
        additional_data:
          $ref: '#/components/schemas/AdditionalData'
        external_id:
          $ref: '#/components/schemas/ExternalID'
        accrual_frequency:
          $ref: '#/components/schemas/AccrualFrequency'
      required:
        - asset_id
        - registration_mode
        - asset_type
        - issuing_date
        - maturity_date
        - issued_units
        - unit_value
        - index_type
        - index_rate
        - customer_type
        - customer_name
        - document_number
        - deposit_number
        - early_redemption_terms
        - currency
    AssetBalance:
      type: object
      properties:
        units:
          $ref: '#/components/schemas/Units'
        redeemed_units:
          $ref: '#/components/schemas/RedeemedUnits'
        units_available:
          $ref: '#/components/schemas/UnitsAvailable'
        latest_accrual_date:
          $ref: '#/components/schemas/LatestAccrualDate'
        daily_rate:
          $ref: '#/components/schemas/DailyRate'
        accum_daily_rate:
          $ref: '#/components/schemas/AccumDailyRate'
        factor:
          $ref: '#/components/schemas/Factor'
        unit_value:
          $ref: '#/components/schemas/UnitValue'
        current_amount:
          $ref: '#/components/schemas/CurrentAmount'
        currency:
          $ref: '#/components/schemas/Currency'
        status:
          $ref: '#/components/schemas/Status'
        position_date:
          $ref: '#/components/schemas/PositionDate'
        accrual_frequency:
          $ref: '#/components/schemas/AccrualFrequency'
    AssetBlock:
      title: AssetBlock
      example:
        units: 50
        document_number: '83759935060'
        status: BLOCK
        external_id: cac02d17-2587-4a7e-ae6a-b449049a8529
        reason: Test block 50 units
      type: object
      properties:
        units:
          $ref: '#/components/schemas/Units'
        document_number:
          $ref: '#/components/schemas/DocumentNumber'
        status:
          $ref: '#/components/schemas/AssetBlockStatus'
        external_id:
          $ref: '#/components/schemas/ExternalID'
        reason:
          $ref: '#/components/schemas/BlockedReason'
      required:
        - units
        - document_number
    AssetBlockStatus:
      type: string
      description: Asset block status
      enum:
        - BLOCK
        - UNBLOCK
      example: BLOCK
    AssetID:
      type: string
      description: >-
        Asset ID. This ID is client-generated. It must be between 1 and 128
        characters long and consist of only the characters [a-z,A-Z,0-9,-,:].
      minLength: 1
      maxLength: 128
      example: 6ea8094b-73ba-4737-93ad-370c27c54813
    AssetMigrate:
      type: object
      properties:
        asset_type:
          $ref: '#/components/schemas/AssetType'
        document_number:
          $ref: '#/components/schemas/DocumentNumber'
        deposit_number:
          $ref: '#/components/schemas/DepositNumber'
    AssetType:
      type: string
      description: >-
        Asset type, `cdb` (certificate of deposit) or `rdb` (bank deposit
        receipt)
      enum:
        - cdb
        - rdb
      example: cdb
    AssetQuotasResponse:
      type: object
      properties:
        current_page:
          $ref: '#/components/schemas/CurrentPage'
        per_page:
          $ref: '#/components/schemas/PerPage'
        pages:
          $ref: '#/components/schemas/Pages'
        total_items:
          $ref: '#/components/schemas/TotalItems'
        items:
          type: array
          items:
            type: object
            properties:
              asset_id:
                $ref: '#/components/schemas/AssetID'
              quota_id:
                $ref: '#/components/schemas/QuotaID'
              issuer_id:
                $ref: '#/components/schemas/IssuerID'
              units:
                $ref: '#/components/schemas/Units'
              redeemed_units:
                $ref: '#/components/schemas/RedeemedUnits'
              created_at:
                $ref: '#/components/schemas/CreatedAt'
              customer_type:
                $ref: '#/components/schemas/CustomerType'
              document_number:
                $ref: '#/components/schemas/DocumentNumber'
              deposit_number:
                $ref: '#/components/schemas/DepositNumber'
    AssetRedemption:
      title: AssetRedemption
      example:
        units: 50
        document_number: '83759935060'
        deposit_number: 9999999
        external_id: cac02d17-2587-4a7e-ae6a-b449049a8529
        redemption_date: '2022-07-01'
      type: object
      properties:
        units:
          $ref: '#/components/schemas/Units'
        document_number:
          $ref: '#/components/schemas/DocumentNumber'
        external_id:
          $ref: '#/components/schemas/ExternalID'
        redemption_date:
          $ref: '#/components/schemas/RedemptionDate'
        deposit_number:
          $ref: '#/components/schemas/DepositNumber'
      required:
        - external_id
        - units
        - document_number
    AssetRedemptionsResponse:
      type: object
      properties:
        current_page:
          $ref: '#/components/schemas/CurrentPage'
        per_page:
          $ref: '#/components/schemas/PerPage'
        pages:
          $ref: '#/components/schemas/Pages'
        total_items:
          $ref: '#/components/schemas/TotalItems'
        items:
          type: array
          items:
            type: object
            properties:
              redemption_id:
                $ref: '#/components/schemas/RedemptionID'
              asset_id:
                $ref: '#/components/schemas/AssetID'
              issuer_id:
                $ref: '#/components/schemas/IssuerID'
              document_number:
                $ref: '#/components/schemas/DocumentNumber'
              deposit_number:
                $ref: '#/components/schemas/DepositNumber'
              redeemed_units:
                $ref: '#/components/schemas/RedeemedUnits'
              currency:
                $ref: '#/components/schemas/Currency'
              redemption_date:
                $ref: '#/components/schemas/RedemptionDate'
              created_at:
                $ref: '#/components/schemas/CreatedAt'
              external_id:
                $ref: '#/components/schemas/ExternalID'
    AssetRegistration:
      title: AssetRegistration
      example:
        asset_id: cac02d17-2587-4a7e-ae6a-b449049a8529
        registration_mode: many
        asset_type: cdb
        issuing_date: '2021-04-16'
        maturity_date: '2021-04-20'
        purchased_units: 10
        issued_units: 1000
        unit_value: 9.99
        index_type: di
        index_rate: 1
        customer_type: natural
        customer_name: Al Fresco
        document_number: '83759935060'
        deposit_number: 9999999
        early_redemption_terms: 'no'
        currency: '986'
        external_id: external-test-cac02d17-2587-4a7e-ae6a-b449049a8529
        accrual_frequency: daily
      properties:
        asset_id:
          $ref: '#/components/schemas/AssetID'
        registration_mode:
          $ref: '#/components/schemas/RegistrationMode'
        asset_type:
          $ref: '#/components/schemas/AssetType'
        issuing_date:
          $ref: '#/components/schemas/IssuingDate'
        maturity_date:
          $ref: '#/components/schemas/MaturityDate'
        issued_units:
          $ref: '#/components/schemas/IssuedUnits'
        unit_value:
          $ref: '#/components/schemas/UnitValue'
        index_type:
          $ref: '#/components/schemas/IndexType'
        index_rate:
          $ref: '#/components/schemas/IndexRate'
        customer_type:
          $ref: '#/components/schemas/CustomerType'
        document_number:
          $ref: '#/components/schemas/DocumentNumber'
        deposit_number:
          $ref: '#/components/schemas/DepositNumber'
        early_redemption_terms:
          $ref: '#/components/schemas/EarlyRedemptionTerms'
        currency:
          $ref: '#/components/schemas/Currency'
        customer_name:
          $ref: '#/components/schemas/CustomerName'
        purchased_units:
          $ref: '#/components/schemas/PurchasedUnits'
        additional_data:
          $ref: '#/components/schemas/AdditionalData'
        external_id:
          $ref: '#/components/schemas/ExternalID'
        accrual_frequency:
          $ref: '#/components/schemas/AccrualFrequency'
      required:
        - asset_id
        - registration_mode
        - asset_type
        - issuing_date
        - maturity_date
        - issued_units
        - unit_value
        - index_type
        - index_rate
        - customer_type
        - document_number
        - deposit_number
        - early_redemption_terms
        - currency
    AssetRegistrationResponse:
      title: AssetRegistrationResponse
      type: object
      properties:
        asset_id:
          $ref: '#/components/schemas/AssetID'
        message:
          $ref: '#/components/schemas/Message'
      required:
        - asset_id
        - message
    AssetUpdateResponse:
      type: object
      properties:
        asset_id:
          $ref: '#/components/schemas/AssetID'
        asset_type:
          $ref: '#/components/schemas/AssetType'
        issuer_id:
          $ref: '#/components/schemas/IssuerID'
        isin_code:
          $ref: '#/components/schemas/IsinCode'
        registration_mode:
          $ref: '#/components/schemas/RegistrationMode'
        issuing_date:
          $ref: '#/components/schemas/IssuingDate'
        maturity_date:
          $ref: '#/components/schemas/MaturityDate'
        created_at:
          $ref: '#/components/schemas/CreatedAt'
        updated_at:
          $ref: '#/components/schemas/UpdatedAt'
        issued_units:
          $ref: '#/components/schemas/IssuedUnits'
        unit_value:
          $ref: '#/components/schemas/UnitValue'
        index_type:
          $ref: '#/components/schemas/IndexType'
        index_rate:
          $ref: '#/components/schemas/IndexRate'
        status:
          $ref: '#/components/schemas/Status'
        currency:
          $ref: '#/components/schemas/Currency'
        early_redemption_terms:
          $ref: '#/components/schemas/EarlyRedemptionTerms'
        interest_rate:
          $ref: '#/components/schemas/InterestRate'
        additional_data:
          $ref: '#/components/schemas/AdditionalData'
    BlockedReason:
      type: string
      description: Reason asset was blocked
      example: Delinquent account
      minLength: 0
      maxLength: 64
    CreatedAt:
      type: string
      description: Date/time (UTC) asset registered on Pismo platform
      example: '2023-03-30T12:26:41'
    Currency:
      type: string
      description: 1SO 4217 currency code
      example: '986'
    CurrentAmount:
      type: number
      format: double
      description: Current amount
      example: 45.8
    CurrentPage:
      type: number
      description: Current page
      example: 1
    CustomerName:
      type: string
      description: Customer name - max length is 128 chars
      minLength: 1
      maxLength: 128
      example: Bud Whyser
    CustomerType:
      type: string
      description: >-
        Customer type - `natural` or `legal`. A `natural` customer is an
        individual, a `legal` customer is a corporation or other legal entitiy
        type.
      enum:
        - natural
        - legal
      example: natural
    DailyRate:
      type: number
      format: double
      description: Daily rate
      example: 1.2
    Date:
      type: string
      description: Redemption date, format = yyyy/mm/dd.
      example: 2023/03/22
    DepositNumber:
      type: integer
      format: int32
      description: Deposit number
      example: 567339022
    DocumentNumber:
      type: string
      description: >
        A government document number, such as a social security number (US).
        Must be numeric with 11-14 digits.
      minLength: 1
      maxLength: 14
      example: '123412341234'
    EarlyRedemptionAttribute:
      title: EarlyRedemptionAttribute
      example:
        date: '2021-02-01'
        interest_rate: 1.09
        floating_rate: 1.18
      type: object
      properties:
        date:
          $ref: '#/components/schemas/Date'
        interest_rate:
          $ref: '#/components/schemas/InterestRate'
        floating_rate:
          $ref: '#/components/schemas/FloatingRate'
    EarlyRedemptionTerms:
      type: string
      description: |
        Early redemption terms:
        * `yes` — Has early redemption terms
        * `no` — Does not have early redemption terms
        * `market` — Redeem at market
      enum:
        - 'yes'
        - 'no'
        - market
      example: market
    ExternalID:
      type: string
      description: >-
        Client-provided external asset ID. No longer than 128 alphanumeric
        characters.
      example: 93830-FFFF-84940
      minLength: 0
      maxLength: 128
    Factor:
      type: string
      description: >
        Calculated pre-rate factor based on how many days the asset has accrued
        (base unit value x factor = new unit value accrued). The pre-rate factor
        is used to calculate how much ROI the customer can expect to receive.
    FloatingRate:
      type: number
      format: double
      description: Floating rate
      example: 2.33
    IndexRate:
      type: number
      format: double
      description: Index rate
      example: 2
    IndexType:
      type: string
      description: >
        Index type:

        * `di` — DI rate is the average rate of interbank transactions carried
        out through interbank certificates of deposits. It is calculated based
        on fixed interbank deposits transactions settled within one business
        day.

        * `ipca` — The Extended National Consumer Price Index (IPCA) is the
        reference for the Brazilian inflation-targeting system. The Banco
        Central do Brasil (BCB) works to ensure that the IPCA's annual inflation
        is centered at the inflation target set by the National Monetary Council
        (CMN). The IPCA is also the price index of the National Treasury's Notes
        Series B (NTN-B).  

        * `pre` — Use when there is a tax defined for the asset.
      enum:
        - di
        - pre
        - ipca
      example: pre
    InterestRate:
      type: number
      format: double
      description: Interest rate
      example: 2.3
    IsinCode:
      type: string
      description: >
        An International Securities Identification Number (ISIN) uniquely
        identifies a security. Its structure is defined in ISO 6166. The ISIN
        code is a 12-character alphanumeric code that serves for uniform
        identification of a security through normalization of the assigned
        National Number, where one exists, at trading and settlement. 
      example: isin12341234
    IssuerID:
      type: string
      description: >
        Issuer ID. For more information, see [issuer identification
        number](https://www.investopedia.com/terms/i/issuer-identification-number-iin.asp)
      example: 98400-0-0d
    IssuingDate:
      type: string
      description: Issuing date, format = yyyy/mm/dd.
      example: 2023/03/22
    IssuedUnits:
      type: integer
      format: int32
      description: Number of issued units
      example: 10
    LatestAccrualDate:
      type: string
      description: Latest accrual date, format = yyyy/mm/dd.
      example: 2023/03/22
    MaturityDate:
      type: string
      description: Asset maturity date, format = yyyy/mm/dd.
      example: 2023/03/22
    Message:
      type: string
      description: Message about asset/quote operation
      example: Message about request operation
      minLength: 0
      maxLength: 128
    OperationType:
      type: string
      description: Quota operation type. Must be `amendment` (update quota).
      enum:
        - amendment
    Pages:
      type: integer
      format: Int32
      description: Total number of pages, default is 1.
      example: 1
    PerPage:
      type: integer
      description: Number of items per page, default is 10.
      format: Int32
      example: 1
    PositionDate:
      type: string
      description: Updated position date, format = yyyy/mm/dd.
      example: '2023-03-22'
    PurchasedUnits:
      type: integer
      format: int32
      description: Number of purchased units
      example: 20
    QuotaID:
      type: string
      description: Quota ID
      example: c2d581cb-5c9c-40ab-8783-724feb372132
    RedeemedUnits:
      type: number
      description: Number of redeemed units
      example: 10
    RedemptionDate:
      type: string
      description: Redemption date, format = yyyy/mm/dd
      example: 2023/03/30
    RedemptionID:
      type: string
      description: Redemption ID
      example: d72a234c-9cbe-4ad0-9b7c-8dd18e958bc0
    RegistrationMode:
      type: string
      description: Registration mode — `single` or `many`
      enum:
        - single
        - many
      example: single
    Status:
      type: string
      description: Asset status
      enum:
        - ACTIVE
        - BLOCKED
        - PENDING
        - CANCELED
        - COMPLETED
        - REDEEMED
      example: ACTIVE
    TotalItems:
      type: number
      description: Total number of items
      example: 1
    Units:
      type: integer
      format: int32
      description: Number of asset units
      example: 20
    UnitValue:
      type: number
      format: double
      description: Per unit value
      example: 65.56
    UpdateAsset:
      title: UpdateAsset
      example:
        operation_type: amendment
        early_redemption_terms: 'yes'
        additional_data:
          early_redemption_attributes:
            - date: '2021-02-01'
              interest_rate: 1.09
              floating_rate: 1.18
            - date: '2021-03-01'
              interest_rate: 100000000000001.1
              floating_rate: 1.15
      type: object
      properties:
        operation_type:
          $ref: '#/components/schemas/OperationType'
        early_redemption_terms:
          $ref: '#/components/schemas/EarlyRedemptionTerms'
        additional_data:
          $ref: '#/components/schemas/AdditionalData'
      required:
        - operation_type
    UpdatedAt:
      type: string
      description: Date/time (UTC) asset last updated on Pismo platform
      example: '2023-03-30T12:26:41'
    UpdateQuota:
      title: UpdateQuota
      example:
        operation_type: amendment
        purchased_units: 1
        customer_name: Patti Waggin
      type: object
      properties:
        operation_type:
          $ref: '#/components/schemas/OperationType'
        purchased_units:
          $ref: '#/components/schemas/PurchasedUnits'
        customer_name:
          $ref: '#/components/schemas/CustomerName'
      required:
        - operation_type
    UpdateQuotaResponse:
      type: object
      properties:
        asset_id:
          $ref: '#/components/schemas/AssetID'
        quota_id:
          $ref: '#/components/schemas/QuotaID'
        issuer_id:
          $ref: '#/components/schemas/IssuerID'
        units:
          $ref: '#/components/schemas/Units'
        created_at:
          $ref: '#/components/schemas/CreatedAt'
        customer_type:
          $ref: '#/components/schemas/CustomerType'
        document_number:
          $ref: '#/components/schemas/DocumentNumber'
        customer_name:
          $ref: '#/components/schemas/CustomerName'
        deposit_number:
          $ref: '#/components/schemas/DocumentNumber'
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    202AssetBlockedResponse:
      description: Accepted
    202AssetMigrateResponse:
      description: ACCEPTED
      content:
        application/json:
          schema:
            type: object
            properties:
              asset_id:
                $ref: '#/components/schemas/AssetID'
              message:
                $ref: '#/components/schemas/Message'
    400BadRequest:
      description: Bad Request
    401Unauthorized:
      description: Unauthorized
    500InternalServerError:
      description: Internal server error
    404NotFound:
      description: Not found
paths:
  /v1/issuer/{issuer_id}/assets:
    post:
      summary: Register banking asset
      description: >
        Register a banking asset with the Pismo platform. A banking asset is
        either a certificate of deposit or a bank receipt.


        This endpoint generates an [Asset registration
        succeeded](https://developers.pismo.io/events/docs/assets-asset-registration-success-1)
        event if it succeeds or an [Asset registration
        failed](https://developers.pismo.io/events/docs/assets-asset-registration-failure-1)
        event if it doesn't.
      tags:
        - Assets
      operationId: AssetRegistration
      parameters:
        - $ref: '#/components/parameters/CorrelationID'
        - $ref: '#/components/parameters/IssuerID'
      requestBody:
        description: Requested body of authorization
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssetRegistration'
      responses:
        '202':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetRegistrationResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
  /v1/issuer/{issuer_id}/assets/{asset_id}:
    get:
      summary: Get banking asset
      description: Get banking asset using issuer and asset IDs
      tags:
        - Assets
      operationId: AssetbyId
      parameters:
        - $ref: '#/components/parameters/CorrelationID'
        - $ref: '#/components/parameters/IssuerID'
        - $ref: '#/components/parameters/AssetID'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Asset'
    patch:
      summary: Update banking asset
      description: >
        Update a banking asset using issuer and asset IDs


        This endpoint generates an [Asset
        updated](https://developers.pismo.io/events/docs/assets-asset-update-1)
        event.
      tags:
        - Assets
      operationId: UpdateAsset
      parameters:
        - $ref: '#/components/parameters/CorrelationID'
        - $ref: '#/components/parameters/IssuerID'
        - $ref: '#/components/parameters/AssetID'
      requestBody:
        description: Request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAsset'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetUpdateResponse'
    delete:
      summary: Delete banking asset
      description: >
        Delete a banking asset previously registered with the Pismo platform


        This endpoint generates an [Asset status
        changed](https://developers.pismo.io/events/docs/assets-asset-status-change-1)
        event.
      tags:
        - Assets
      operationId: AssetCancellation
      parameters:
        - $ref: '#/components/parameters/CorrelationID'
        - $ref: '#/components/parameters/IssuerID'
        - $ref: '#/components/parameters/AssetID'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Asset'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
  /v2/issuer/{issuer_id}/assets/{asset_id}/redemption:
    put:
      summary: Create banking asset redemption
      description: >
        Create a banking asset redemption. A banking asset redemption is the
        repayment of the original value of the asset to the investor.


        If the request succeeds, this endpoint generates an [Asset
        redeemed](https://developers.pismo.io/events/docs/assets-asset-redemption-1)
        event and an [Asset status
        changed](https://developers.pismo.io/events/docs/assets-asset-status-change-1)
        event.

        If it fails, it generates an [Asset redemption
        failed](https://developers.pismo.io/events/docs/assets-asset-redemption-failure-1)
        event.
      tags:
        - Assets
      operationId: AssetRedemptionV2
      parameters:
        - $ref: '#/components/parameters/CorrelationID'
        - $ref: '#/components/parameters/IssuerID'
        - $ref: '#/components/parameters/AssetID'
      requestBody:
        description: Request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssetRedemption'
      responses:
        '202':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetRegistrationResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
  /v1/issuer/{issuer_id}/assets/{asset_id}/redemption:
    get:
      summary: List banking asset redemptions
      description: List banking asset redemptions using asset and issuer IDs
      tags:
        - Assets
      operationId: AssetRedemption
      parameters:
        - $ref: '#/components/parameters/CorrelationID'
        - $ref: '#/components/parameters/IssuerID'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PerPage'
        - $ref: '#/components/parameters/AssetID'
        - $ref: '#/components/parameters/ExternalId'
        - $ref: '#/components/parameters/BeginDate'
        - $ref: '#/components/parameters/EndDate'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetRedemptionsResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
  /v1/issuer/{issuer_id}/assets/{asset_id}/quotas/{quota_id}:
    patch:
      summary: Update quota
      description: >
        Updates a quota by its ID.


        A quota is the number of asset shares. One asset can consist of a single
        share or multiple shares. 


        You can get quota IDs with the <a
        href="https://developers.pismo.io/pismo-docs/reference/assetquotas"
        target="_blank">List asset quotas</a> endpoint.


        This endpoint generates a [Quota
        updated](https://developers.pismo.io/events/docs/assets-quota-update-1)
        event.
      tags:
        - Quotas
      operationId: UpdateQuota
      parameters:
        - $ref: '#/components/parameters/CorrelationID'
        - $ref: '#/components/parameters/IssuerID'
        - $ref: '#/components/parameters/AssetID'
        - $ref: '#/components/parameters/QuotaID'
      requestBody:
        description: Request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateQuota'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateQuotaResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
  /v1/issuer/{issuer_id}/assets/{asset_id}/quotas:
    get:
      summary: List asset quotas
      description: >
        Retrieves asset quotas by asset ID. 

        A quota is the number of asset shares. One asset can consist of a single
        share or multiple shares. 
      tags:
        - Quotas
      operationId: AssetQuotas
      parameters:
        - $ref: '#/components/parameters/CorrelationID'
        - $ref: '#/components/parameters/IssuerID'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PerPage'
        - $ref: '#/components/parameters/AssetID'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetQuotasResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
  /v1/issuer/{issuer_id}/assets/{asset_id}/balance:
    get:
      summary: Get banking asset balance
      description: Get banking asset balance using asset ID
      tags:
        - Assets
      operationId: AssetBalance
      parameters:
        - $ref: '#/components/parameters/CorrelationID'
        - $ref: '#/components/parameters/IssuerID'
        - $ref: '#/components/parameters/AssetID'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetBalance'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
  /v1/issuer/{issuer_id}/assets/{asset_id}/block:
    post:
      summary: Block/unblock banking asset
      description: >
        Block or unblock a banking asset


        If the request succeeds, this endpoint generates an [Asset
        blocked](https://developers.pismo.io/events/docs/assets-asset-block-1)
        event;

        otherwise, generates an [Asset block
        failed](https://developers.pismo.io/events/docs/assets-asset-block-failure-1)
        event.
      tags:
        - Assets
      operationId: AssetBlock
      parameters:
        - $ref: '#/components/parameters/CorrelationID'
        - $ref: '#/components/parameters/IssuerID'
        - $ref: '#/components/parameters/AssetID'
      requestBody:
        description: Request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssetBlock'
      responses:
        '202':
          description: ACCEPTED
          content:
            application/json:
              schema:
                $ref: '#/components/responses/202AssetBlockedResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
  /v1/issuer/{issuer_id}/assets/{asset_id}/migrate:
    post:
      summary: Migrate banking asset
      description: >
        Migrate banking asset


        If the request succeeds, this endpoint generates an <a
        href="https://json-schemas.data.pismo.io/docs/assets/asset_block-1.html">asset_block-1</a>
        event.

        If it fails, it generates an <a
        href="https://json-schemas.data.pismo.io/docs/assets/asset_block_failure-1.html">asset_block_failure-1</a>
        event.
      tags:
        - Assets
      operationId: postAssetBlock
      parameters:
        - $ref: '#/components/parameters/CorrelationID'
        - $ref: '#/components/parameters/IssuerID'
        - $ref: '#/components/parameters/AssetID'
      requestBody:
        description: Request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssetMigrate'
      responses:
        '202':
          $ref: '#/components/responses/202AssetMigrateResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
