openapi: 3.1.0
info:
  title: Core platform - Accounting
  version: 1.0.0
  description: API used to manage the accounting context
  contact:
    name: API Support
    url: https://developers.pismo.io/support/
  license:
    name: Copyright Pismo
servers:
  - url: https://sandbox.pismolabs.io/accounting
    description: Sandbox API server for testing
components:
  schemas:
    AccountingAccount:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Accounting account ID
        description:
          type: string
          description: Description of the accounting account
          maximum: 100
        account:
          type: string
          description: Accounting account number
          maximum: 50
        program_id:
          type: integer
          format: int64
          description: Program ID
        created_at:
          type: string
          format: date-time
          description: Date and time when the accounting account was created (ISO 8601).
        deactivated_at:
          type: string
          format: date-time
          description: >-
            Date and time when the accounting account was deactivated (ISO
            8601). Filled when the account is deactivated.
      example:
        id: 1
        description: SAMPLE ACCOUNT
        account: 123123132-x
        program_id: 12
        created_at: '2021-10-10T10:10:00.000Z'
    AccountingAccountAccountSctiptPost:
      required:
        - description
        - account
      type: object
      properties:
        description:
          type: string
          description: >-
            Description that helps to identify the accounting account.  Can be
            `0` or any value if there's no corresponding account.
          maximum: 100
        account:
          type: string
          description: >-
            Accounting account number.  Can be `0` or any value if there's no
            corresponding account.
          maximum: 50
      example:
        description: SAMPLE ACCOUNT
        account: 123123132-x
    AccountingAccountPatch:
      required:
        - description
      type: object
      properties:
        description:
          type: string
          description: Description that helps to identify the accounting account
          maximum: 100
      example:
        description: SAMPLE ACCOUNT
    AccountingAccountPost:
      required:
        - description
        - account
        - program_id
      type: object
      properties:
        description:
          type: string
          description: >-
            Description that helps to identify the accounting account.  Can be
            `0` or any value if there's no corresponding account.
          maximum: 100
        account:
          type: string
          description: >-
            Accounting account number. Can be `0` or any value if there's no
            corresponding account.
          maximum: 50
        program_id:
          type: integer
          format: int64
          description: Related program ID
      example:
        description: SAMPLE ACCOUNT
        account: 123123132-x
        program_id: 12
    AccountingEntryPost:
      required:
        - event_date
        - program_id
        - entry_type_id
        - amount
      type: object
      properties:
        amount:
          type: number
          description: Accounting entry amount
        entry_type_id:
          type: integer
          format: int64
          description: Entry type ID
        event_date:
          type: string
          format: date
          description: Event date
          example: '2021-06-26'
        program_id:
          type: integer
          format: int64
          description: Related program ID
        account_id:
          type: integer
          format: int64
          description: Related account ID, required if Transaction_ID is present.
        credit_accounting_account:
          type: string
          description: Credit accounting account
        debit_accounting_account:
          type: string
          description: Debit accounting account
        tracking_id:
          type: string
          description: >-
            Tracking ID in UUID format, optional idempotence key. You can use
            [Online UUID Generator](https://www.uuidgenerator.net/version4) to
            generate a random UUID value.
          maximum: 50
        transaction_id:
          type: integer
          format: int64
          description: Related transaction ID
      example:
        amount: 10
        entry_type_id: 2100
        event_date: '2021-02-01T00:00:00.000Z'
        program_id: 12
        account_id: 21
        credit_accounting_account: '0'
        debit_accounting_account: '0'
        tracking_id: c5f2f677-d9aa-4285-8a08-d297a72d8949
        transaction_id: 12342
    AccountingScript:
      type: object
      properties:
        credit_accounting:
          $ref: '#/components/schemas/AccountingAccount'
        cost_center:
          $ref: '#/components/schemas/CostCenter'
        debit_accounting:
          $ref: '#/components/schemas/AccountingAccount'
        entry_name:
          type: string
          description: Base entry ID
        entry_type_id:
          type: integer
          format: int64
          description: Related entry type ID
        event_type_id:
          type: integer
          format: int64
          description: Related event type ID
        id:
          type: integer
          format: int64
          description: Account script ID
        processing_code:
          type: string
          description: >-
            Processing code. When the script is based on a processing code, this
            field is **REQUIRED**.
        program_id:
          type: integer
          format: int64
          description: Related program ID
    AccountingScriptBucket:
      type: object
      properties:
        name:
          type: string
          description: Bucket name
          example: bacen_pre_2039
        account:
          type: integer
          format: int64
          description: Account ID
          example: 123456
    AccountingScriptBucketResponse:
      type: object
      properties:
        name:
          type: string
          description: Bucket name
          example: bacen_pre_2039
        account:
          type: integer
          format: int64
          description: Account ID
          example: 123456
        currency:
          type: string
          description: Bucket currency
          example: BRL
        value:
          type: number
          description: Bucket value
          example: 100
    AccountingScriptParameters:
      required:
        - name
        - value
      type: object
      properties:
        name:
          type: string
          description: Parameter name [pismo:timing or bacen:classification]
          example: pismo:timing
        value:
          type: string
          description: Parameter value [REGULAR, DUEDATE, TRUE, or 3]
          example: REGULAR, DUEDATE
    AccountingScriptPatch:
      type: object
      properties:
        debit_account_number:
          type: string
          description: Debit account accounting number
        credit_account_number:
          type: string
          description: Credit account accounting number
        debit_cost:
          type: string
          description: Debit cost center
        credit_cost:
          type: string
          description: Credit cost center
    AccountingScriptPatchResponse:
      type: object
      additionalProperties:
        type: object
        properties:
          has_error:
            description: Indicates whether an error occurred during the update process.
            type: boolean
          error_message:
            description: Provides a detailed description of the error encountered, if any.
            type: string
          new_id:
            type: integer
            format: int64
            description: >-
              Unique identifier of the newly created accounting script. (The old
              one will be deactivated)
    AccountingScriptPost:
      required:
        - program_id
        - event_type_id
        - entry_type_id
        - debit_accounting_account_id
        - credit_accounting_account_id
      type: object
      properties:
        entry_type_id:
          type: integer
          format: int64
          description: Related entry type ID
        event_type_id:
          type: integer
          format: int64
          description: Related event type ID
        credit_accounting_account_id:
          type: integer
          format: int64
          description: Accounting account ID assigned as credit account
        debit_accounting_account_id:
          type: integer
          format: int64
          description: Accounting account ID assigned as debit account
        program_id:
          type: integer
          format: int64
          description: Related program ID
        cost_center:
          $ref: '#/components/schemas/CostCenter'
        entry_name:
          type: string
          enum:
            - amount
            - amount-advancement
            - amount-advancement-dueDate
            - amount-advancement-shift
            - amount-advancement-shift-dueDate
            - amount-anticipation
            - amount-cancelment-anticipation
            - amount-clearing
            - amount-contract
            - amount-dueDate
            - amount-dueDate-cancelment
            - amount-reversal
            - contractAmount
            - daily-interest
            - fine
            - interest
            - interest-advancement
            - interest-advancement-dueDate
            - interest-anticipation
            - interest-dueDate
            - interest-not-appropriated
            - interest-partial
            - iof
            - iof-dueDate
            - overdue
          default: amount
          description: >
            Base entry ID. If not provided, defaults to 'amount'.

            * `amount`: Principal amount of the transaction on the event date.
            It usually represents the gross value of the operation associated
            with the corresponding flow/`entry_type`.

            * `amount-advancement`: Principal amount of the advance (excluding
            interest/charges), that is, the principal being advanced (for
            example, installment agreement advance, invoice advance, receivables
            advance).

            * `amount-advancement-dueDate`: Principal amount of the advance,
            posted on the due date of the cycle to which the transaction was
            advanced.

            * `amount-advancement-shift`: Principal amount of the advance using
            the “shift” API (date change / flow adjustment), for example advance
            of an installment or invoice where there is a replacement/change of
            the original flow. Used to represent the principal of the
            installment/amount that is being moved from a future date to a
            present date through an advance.

            * `amount-advancement-shift-dueDate`: Same concept as
            `amount-advancement-shift`, but related to the due date. It
            represents the principal of the advance associated with the original
            due date of the obligation that was “shifted” (moved/adjusted) by
            the advance process.

            * `amount-anticipation`: This amount name is deprecated. Standard
            routings that were eventually created with it are deprecated and
            have corresponding routings with `-advancement` amount values.

            * `amount-cancelment-anticipation`: This amount name is deprecated.
            Standard routings that were created with it are deprecated and have
            corresponding routings with `-advancement` amount values.

            * `amount-clearing`: Amount used exclusively for configuring the
            posting of the installment principal (without interest) upon the
            clearing arrival of each installment.

            * `amount-contract`: This amount name is deprecated. Standard
            routings that were created with it are deprecated and have
            corresponding routings with `amount` values.

            * `amount-dueDate`: Principal amount of the transaction related to
            the due date (for example, an installment or invoice that is due).
            Used when the amount to be posted is linked to a specific due date,
            even if the event occurs before that date. It represents the due
            date posting of the `amount`. 

            * `amount-dueDate-cancelment`: This amount name is deprecated. 

            * `amount-reversal`: This amount name is deprecated and has no
            corresponding movement, as there are no mapped usage scenarios for
            it.

            * `contractAmount`: This amount is deprecated. The transactions for
            which it may be configured are transactions 608 and 612. If it is
            currently used, the recommendation is to create routings with
            `amount`, which will return the total transaction value. Used as a
            reference for the total obligation assumed at the time of
            contracting.

            * `daily-interest`: Amount of daily interest calculated for a period
            (for example, between two specific dates), usually used in scenarios
            such as pro-rata interest calculation.

            * `fine`: Fine amount included in a payment (amount that is
            discharged). This type should only be used when linked to
            transaction 201 (payment). When used, it provides details of how
            much of that payment corresponds to the fine.

            * `interest`: Amount of interest calculated/incurred on the
            transaction, whether it is a contract transaction or an installment.
            Important: this should only be used if the interest is included
            together with the transaction's total amount, so that the `interest`
            is explicitly identified as such. If the interest is already in a
            separate transaction, `amount` should be used instead.

            * `interest-advancement`: Interest amount related to the advance
            operation, for example, interest amount of an advanced installment.

            * `interest-advancement-dueDate`: Interest amount of the advance,
            posted on the due date of the cycle to which the transaction was
            advanced.

            * `interest-anticipation`: This amount name is deprecated. Standard
            routings that were created with it are deprecated and have
            corresponding routings with `-advancement` amount values.

            * `interest-dueDate`: Interest amount of an operation at the due
            date. The usage logic is the same as for `interest`, but in this
            case the posting occurs on the due date.

            * `interest-not-appropriated`: Amount exclusively used for posting
            interest from transaction 706 (invoice installment cancellation). It
            obtains the interest amount to be posted from the original
            contracting transaction.

            * `interest-partial`: This amount name is deprecated and has been
            replaced by `daily-interest`.

            * `iof`: IOF amount (financial transactions tax) associated with the
            event operation. As with interest, the same logic applies: if the
            IOF is already in a specific and separate transaction, this option
            should not be used, and `amount` is the correct option.

            * `iof-dueDate`: IOF amount (financial transactions tax) associated
            with the event operation. As with interest, the same logic applies:
            if the IOF is already in a specific and separate transaction, this
            option should not be used, and `amount`` is the correct option. This
            due-date option posts the value on the due date of the invoice that
            contains the transaction.

            * `overdue`: Late interest (penalty interest) amount included in a
            payment (amount that is discharged). This type should only be used
            when linked to transaction 201 (payment). When used, it provides
            details of how much of that payment corresponds to late interest.
        processing_code:
          type: string
          maximum: 6
          description: >-
            Processint code. When the script is based on a processing code, this
            field is **REQUIRED**.
    AccountingScriptSinglePatchResponse:
      type: object
      properties:
        new_id:
          type: integer
          format: int64
          description: >-
            Unique identifier of the newly created accounting script. (The old
            one will be deactivated)
    AccountingScriptV2:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Accounting script ID
        program_id:
          type: integer
          format: int64
          description: Program ID
        event_type_id:
          type: integer
          format: int64
          description: Event type ID
        entry_type_id:
          type: integer
          format: int64
          description: Entry type ID
        debit_accounting:
          $ref: '#/components/schemas/AccountingAccountAccountSctiptPost'
        credit_accounting:
          $ref: '#/components/schemas/AccountingAccountAccountSctiptPost'
        cost_center:
          $ref: '#/components/schemas/CostCenterAccountingScriptPost'
        processing_code:
          type: string
          description: Processing code
        expression:
          type: string
          description: >
            Expression to calculate the value of the accounting entry.

            It can be a simple mathematical expression or a more complex one
            using functions.
        fee_information:
          type: object
          description: |
            Information about the fee applied to the accounting entry.
            It can include details such as fee type, amount, and currency.
        parameters:
          $ref: '#/components/schemas/AccountingScriptParameters'
        cash_in_bucket:
          $ref: '#/components/schemas/AccountingScriptBucket'
        cash_out_bucket:
          $ref: '#/components/schemas/AccountingScriptBucket'
        is_database_stage:
          type: string
          description: >
            Indicates if the accounting script is for a database stage.

            If yes, the script is used for testing purposes and does not affect
            production data.
          default: 'no'
          example: 'yes'
        min_days_due:
          type: integer
          format: int64
          description: Minimum number of days for the due date
          example: 30
        max_days_due:
          type: integer
          format: int64
          description: Maximum number of days for the due date
          example: 90
        history:
          $ref: '#/components/schemas/History'
    AccountingScriptPostV2:
      type: object
      required:
        - entry_type_id
        - debit_accounting
        - credit_accounting
        - expression
      properties:
        credit_accounting:
          $ref: '#/components/schemas/AccountingAccountAccountSctiptPost'
        debit_accounting:
          $ref: '#/components/schemas/AccountingAccountAccountSctiptPost'
        entry_type_id:
          $ref: '#/components/schemas/EntryTypePost'
        expression:
          type: string
          description: >
            Expression to calculate the value of the accounting entry.

            It can be a simple mathematical expression or a more complex one
            using functions.
        cash_in_bucket:
          $ref: '#/components/schemas/AccountingScriptBucket'
        cash_out_bucket:
          $ref: '#/components/schemas/AccountingScriptBucket'
        cost_center:
          $ref: '#/components/schemas/CostCenterAccountingScriptPost'
        event_type_id:
          type: integer
          format: int64
          description: Event type ID
        except_program_ids:
          items:
            type: integer
            description: List of program IDs to exclude
          example:
            - 78
            - 91
        fee_information:
          type: object
          description: |
            Information about the fee applied to the accounting entry.
            It can include details such as fee type, amount, and currency.
        is_database_stage:
          type: string
          description: >
            Is this accounting script for database staging?

            If yes, the script is used for testing purposes and does not affect
            production data.
          default: 'no'
          example: 'yes'
        max_days_due:
          type: integer
          format: int64
          description: Maximum number of days for the due date
          example: 90
        min_days_due:
          type: integer
          format: int64
          description: Minimum number of days for the due date
          example: 30
        parameters:
          $ref: '#/components/schemas/AccountingScriptParameters'
        processing_code:
          type: string
          description: Processing code
        program_id:
          type: integer
          format: int64
          description: Program ID
        program_list_id:
          type: array
          items:
            type: integer
            description: List of program IDs to include
          example:
            - 12
            - 34
            - 56
        program_types:
          type: array
          items:
            type: string
            description: Program types
          example:
            - CREDIT
            - DEBIT
        reason:
          $ref: '#/components/schemas/HistoryReason'
        responsible:
          $ref: '#/components/schemas/HistoryResponsible'
    BatchAccountingScriptPatch:
      type: object
      properties:
        operations:
          type: array
          items:
            properties:
              accounting_script_id:
                type: integer
                format: int64
                description: Accounting script ID
              set:
                $ref: '#/components/schemas/AccountingScriptPatch'
    Bucket:
      type: object
      properties:
        name:
          type: string
          description: Bucket name
          example: bacen_pre_2039
        account:
          type: integer
          format: int64
          description: Account ID
          example: 123456
        value:
          type: number
          description: Bucket value
          example: 100
        updated_at:
          type: string
          format: date
          description: Bucket last updated date
          example: '2021-06-26'
    CostCenter:
      required:
        - debit_org
        - credit_org
        - debit_cost
        - credit_cost
      type: object
      properties:
        debit_org:
          type: string
          maximum: 50
          description: Number of your Org’s debit accounting account
        credit_org:
          type: string
          maximum: 50
          description: Number of your Org’s credit accounting account
        debit_cost:
          type: string
          maximum: 50
          description: Number of the cost center of the debit accounting account
        credit_cost:
          type: string
          maximum: 50
          description: Number of the cost center of the credit accounting account
        deactivated_at:
          type: string
          format: date-time
          description: >-
            Date and time when the cost center was deactivated (ISO 8601).
            Filled when the account is deactivated.
      example:
        debit_org: '999999'
        credit_org: '999999'
        debit_cost: '999999'
        credit_cost: '999999'
        deactivated_at: '2021-10-10T10:10:00.000Z'
    CostCenterAccountingScriptPost:
      required:
        - debit_org
        - credit_org
        - debit_cost
        - credit_cost
      type: object
      properties:
        debit_org:
          type: string
          maximum: 50
          description: Number of your Org’s debit accounting account
        credit_org:
          type: string
          maximum: 50
          description: Number of your Org’s credit accounting account
        debit_cost:
          type: string
          maximum: 50
          description: Number of the cost center of the debit accounting account
        credit_cost:
          type: string
          maximum: 50
          description: Number of the cost center of the credit accounting account
      example:
        debit_org: '999999'
        credit_org: '999999'
        debit_cost: '999999'
        credit_cost: '999999'
    EntryType:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/EntryTypeID'
        description:
          $ref: '#/components/schemas/EntryTypeDescription'
        type:
          $ref: '#/components/schemas/EntryTypeType'
        org_id:
          $ref: '#/components/schemas/OrgID'
        history:
          $ref: '#/components/schemas/History'
    EntryTypeDelete:
      required:
        - reason
      type: object
      properties:
        reason:
          $ref: '#/components/schemas/HistoryReason'
        responsible:
          $ref: '#/components/schemas/HistoryResponsible'
      example:
        reason: Deleting accounting entry type configuration.
        responsible: John Doe
    EntryTypeDescription:
      type: string
      maximum: 250
      description: Entry type description.
      example: CREDIT
    EntryTypeGetById:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/EntryTypeID'
        description:
          $ref: '#/components/schemas/EntryTypeDescription'
        type:
          $ref: '#/components/schemas/EntryTypeType'
        reason:
          $ref: '#/components/schemas/HistoryReason'
        responsible:
          $ref: '#/components/schemas/HistoryResponsible'
        history:
          type: array
          items:
            $ref: '#/components/schemas/History'
    EntryTypeID:
      type: integer
      format: int64
      description: Entry type ID
      example: 101
    EntryTypePatch:
      required:
        - reason
      type: object
      properties:
        description:
          $ref: '#/components/schemas/EntryTypeDescription'
        type:
          $ref: '#/components/schemas/EntryTypeType'
        reason:
          $ref: '#/components/schemas/HistoryReason'
        responsible:
          $ref: '#/components/schemas/HistoryResponsible'
      example:
        description: DEBIT
        type: CREATION
        reason: Updating accounting entry type configuration.
        responsible: John Doe
    EntryTypePost:
      required:
        - id
        - description
        - type
        - reason
      type: object
      properties:
        id:
          $ref: '#/components/schemas/EntryTypeID'
        description:
          $ref: '#/components/schemas/EntryTypeDescription'
        type:
          $ref: '#/components/schemas/EntryTypeType'
        reason:
          $ref: '#/components/schemas/HistoryReason'
        responsible:
          $ref: '#/components/schemas/HistoryResponsible'
    EntryTypeType:
      type: string
      maximum: 100
      description: >
        Set the entry type:


        * `CREATION`: Default value for new entries. Also, this value is assumed
        when type is not provided.

        * `DUE_DATE`: Used only with a credit program to indicate a due date
        entry.
      enum:
        - DUE_DATE
        - CREATION
      example: DUE_DATE
    EventType:
      required:
        - id
        - description
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Event type ID
        description:
          type: string
          maximum: 100
          description: Event type description
      example:
        id: 101
        description: CREDIT
    History:
      type: object
      description: Historical information for auditing the entity.
      properties:
        org_id:
          $ref: '#/components/schemas/OrgID'
        action:
          type: string
          description: Action performed on the entity.
          example: Created
        reason:
          $ref: '#/components/schemas/HistoryReason'
        responsible:
          $ref: '#/components/schemas/HistoryResponsible'
        version:
          type: integer
          format: int64
          description: Entity version.
          example: 1
        jsonb:
          type: string
          description: JSON representation of the request body.
          example: >-
            {"id": 101, "description": "CREDIT", "type": "DUE_DATE", "reason":
            "Creation of a new entry type configuration.", "responsible": "John
            Doe", "created_at": "2021-10-10T10:10:00Z"}
        created_at:
          type: string
          format: date-time
          description: >-
            Date and time when the history was created (ISO 8601). Format:
            YYYY-MM-DDThh:mm:ssZ.
          example: '2021-10-10T10:10:00Z'
    HistoryReason:
      type: string
      maximum: 250
      description: Reason for the operation.
      example: Creation of a new entry type configuration.
    HistoryResponsible:
      type: string
      maximum: 100
      description: User name or ID of the person performing the operation.
      example: John Doe
    OrgID:
      type: string
      description: Organization ID
      example: TN-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    Page:
      type: object
      properties:
        has_next:
          type: boolean
          description: Indicates if there are more items to be retrieved.
        items:
          type: array
          description: Items retrieved from a given request.
          items:
            type: object
  parameters:
    pageSize:
      in: query
      name: pageSize
      description: Maximum number of accounting event types per page.
      schema:
        type: integer
    pageOffset:
      name: pageOffset
      in: query
      description: >-
        Number to offset page resuts. For example, value `2` returns the third
        page. Defaults to `0`, which returns the first page.
      schema:
        type: integer
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: >-
        Account access token. Tokens can expire quickly, which can result in an
        "Unauthorized" error.
      bearerFormat: JWT
tags:
  - name: Accounting event types
    description: Endpoints to manage accounting event types.
  - name: Accounting entry types
    description: Endpoints to manage accounting entry types.
  - name: Accounting accounts
    description: >-
      Endpoints to manage the accounting plan, which is a set of accounting
      accounts.
  - name: Accounting scripts V2
    description: Endpoints to manage accounting scripts V2
  - name: Accounting scripts V1
    description: Endpoints to manage accounting scripts V1
  - name: Accounting entry
    description: Endpoints to manage accounting entries.
  - name: Buckets
    description: Endpoints to manage account buckets.
paths:
  /v1/event-types:
    get:
      operationId: SearchEvents
      summary: List accounting event types
      description: >
        List accounting event types for your organization.


        Refer to the [Search for accounting event
        types](doc:search-for-accounting-event-types) for more information.
      tags:
        - Accounting event types
      parameters:
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/pageOffset'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/Page'
                  - properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/EventType'
        '400':
          description: Bad request
      deprecated: false
  /v1/event-types/{eventTypeId}:
    get:
      operationId: GetEventTypeById
      summary: Get accounting event type
      description: >
        Get a specific accounting event type by its ID.


        Refer to the [Search for accounting event
        types](doc:search-for-accounting-event-types) for more information.
      tags:
        - Accounting event types
      parameters:
        - in: path
          name: eventTypeId
          schema:
            type: integer
            format: int64
          required: true
          description: Event type ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventType'
        '404':
          description: Event type not found
      deprecated: false
  /v2/entry-types:
    post:
      operationId: CreateEntryTypeV2
      summary: Create accounting entry types
      description: Create accounting entry type for your organization.
      tags:
        - Accounting entry types
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryTypePost'
      responses:
        '201':
          description: Ok
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/EntryType'
        '400':
          description: Bad request when a provided parameter is invalid
        '409':
          description: Bad request (conflict) when ID already exists
        '500':
          description: Internal server error
    get:
      operationId: SearchEntryTypesV2
      summary: List accounting entry types
      description: >-
        List accounting entry types with their latest history from your
        organization.
      tags:
        - Accounting entry types
      parameters:
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/pageOffset'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/Page'
                  - properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/EntryType'
        '400':
          description: Bad request when a provided parameter is invalid
        '404':
          description: Entry type not found
        '500':
          description: Internal server error
      deprecated: false
  /v2/entry-types/{entryTypeId}:
    get:
      operationId: GetEntryTypeByIdV2
      summary: Get accounting entry type
      description: >-
        Get a specific accounting entry type by its ID with its historic
        information.
      tags:
        - Accounting entry types
      parameters:
        - in: path
          name: entryTypeId
          schema:
            type: integer
            format: int64
          required: true
          description: Numeric entry type ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntryTypeGetById'
        '400':
          description: Bad request when a provided parameter is invalid
        '404':
          description: Entry type not found
        '500':
          description: Internal server error
      deprecated: false
    patch:
      operationId: UpdateEntryTypeV2
      summary: Update accounting entry type
      description: Update a specific accounting entry type by its ID.
      tags:
        - Accounting entry types
      parameters:
        - in: path
          name: entryTypeId
          schema:
            type: integer
            format: int64
          required: true
          description: Numeric entry type ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryTypePatch'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/EntryType'
        '400':
          description: Bad request when a provided parameter is invalid
        '404':
          description: Entry type not found
        '500':
          description: Internal server error
    delete:
      operationId: DeleteEntryTypeV2
      summary: Delete accounting entry type
      description: Delete a specific accounting entry type by its ID.
      tags:
        - Accounting entry types
      parameters:
        - in: path
          name: entryTypeId
          schema:
            type: integer
            format: int64
          required: true
          description: Numeric entry type ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryTypeDelete'
      responses:
        '200':
          description: OK
        '400':
          description: Bad request when a provided parameter is invalid
        '404':
          description: Entry type not found
        '500':
          description: Internal server error
      deprecated: false
  /v1/entry-types:
    get:
      operationId: SearchEntryTypes
      summary: List accounting entry types (outdated)
      description: >
        List accounting entry types from your organization.


        This endpoint is outdated and new endpoint is available: [List
        accounting entry types](ref:searchentrytypesv2).


        Refer to [Search for accounting entry
        types](doc:create-accounting-entries#search-for-accounting-entry-types)
        for more information.
      tags:
        - Accounting entry types
      parameters:
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/pageOffset'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/Page'
                  - properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/EntryType'
        '400':
          description: Bad request
      deprecated: false
  /v1/entry-types/{entryTypeId}:
    get:
      operationId: GetEntryTypeById
      summary: Get accounting entry type (outdated)
      description: >
        Get a specific accounting entry type by its ID.


        This endpoint is outdated and new endpoint is available: [Get accounting
        entry type](ref:getentrytypebyidv2).


        Refer to [Search for accounting entry
        types](doc:create-accounting-entries#search-for-accounting-entry-types)
        for more information.
      tags:
        - Accounting entry types
      parameters:
        - in: path
          name: entryTypeId
          schema:
            type: integer
            format: int64
          required: true
          description: Entry type ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntryType'
        '404':
          description: Entry type not found
      deprecated: false
  /v1/accounting-accounts:
    post:
      operationId: CreateAccountingAccount
      summary: Create accounting account
      description: >
        Create an accounting account.


        Refer to the [How to create accounting
        account](doc:create-an-accounting-account) guide for more information.
      tags:
        - Accounting accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountingAccountPost'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingAccount'
        '400':
          description: Bad request when some provided parameter is invalid.
        '409':
          description: Accounting account already exists.
    get:
      operationId: SearchAccountingAccounts
      summary: List accounting accounts
      description: List accounting accounts for your organization.
      tags:
        - Accounting accounts
      parameters:
        - in: query
          name: account
          description: >-
            Account ID filter to list all accounting accounts related to an
            account.
          schema:
            type: string
        - in: query
          name: programId
          description: >-
            Program ID filter to list all accounting accounts related to a
            program.
          schema:
            type: integer
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/pageOffset'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/Page'
                  - properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/AccountingAccount'
        '400':
          description: Bad request
      deprecated: false
  /v1/accounting-accounts/{accountingAccountId}:
    get:
      operationId: GetAccountingAccountById
      summary: Get accounting account
      description: Get a specific accounting account by its ID.
      tags:
        - Accounting accounts
      parameters:
        - in: path
          name: accountingAccountId
          schema:
            type: integer
            format: int64
          required: true
          description: Accounting account ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingAccount'
        '404':
          description: Accounting account not found.
      deprecated: false
    patch:
      operationId: UpdateAccountingAccount
      summary: Update accounting account
      description: Update description of an accounting account.
      tags:
        - Accounting accounts
      parameters:
        - in: path
          name: accountingAccountId
          schema:
            type: integer
            format: int64
          required: true
          description: Accounting account ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountingAccountPatch'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/AccountingAccount'
        '400':
          description: Bad request when a provided parameter is invalid.
        '404':
          description: Accounting account not found.
    delete:
      operationId: DeleteAccountingAccount
      summary: Delete accounting account
      description: Delete an accounting account.
      tags:
        - Accounting accounts
      parameters:
        - in: path
          name: accountingAccountId
          schema:
            type: integer
            format: int64
          required: true
          description: Accounting account ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                example:
                  id: 1
                  description: SAMPLE ACCOUNT
                  account: 123123132-x
                  program_id: 12
                  created_at: '2021-10-10T10:10:00.000Z'
                  deactivated_at: '2021-10-11T10:10:00.000Z'
        '404':
          description: Accounting account not found
        '409':
          description: >-
            Accounting account cannot be deleted, because it's being used by an
            active accounting script.
  /v2/accounting-scripts:
    post:
      operationId: CreateAccountingScriptV2
      summary: Create accounting script V2
      description: >
        Create an accounting script. 


        Refer to the [How to create accounting
        script](doc:create-an-accounting-script) guide for more information.
      tags:
        - Accounting scripts V2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountingScriptPostV2'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountingScriptV2'
        '400':
          description: Bad request
        '409':
          description: Conflict
      deprecated: false
    get:
      tags:
        - Accounting scripts V2
      summary: List accounting scripts V2
      operationId: listAccountingScriptsV2
      description: |
        List existing accounting scripts for your organization.
      parameters:
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/pageOffset'
        - in: query
          name: debitAccountingAccount
          description: List all accounting scripts related to a debit accounting account
          schema:
            type: string
        - in: query
          name: creditAccountingAccount
          description: List all accounting scripts related to a credit accounting account
          schema:
            type: string
        - in: query
          name: programId
          description: List all accounting scripts related to a program
          schema:
            type: integer
            format: int64
        - in: query
          name: eventTypeId
          description: List all accounting scripts related to an event type
          schema:
            type: integer
            format: int64
        - in: query
          name: entryTypeId
          description: List all accounting scripts related to an entry type
          schema:
            type: integer
            format: int64
        - in: query
          name: cashInBucketName
          description: List all accounting scripts related to a cash-in bucket name
          schema:
            type: integer
            format: int64
        - in: query
          name: cashOutBucketName
          description: List all accounting scripts related to a cash-out bucket name
          schema:
            type: integer
            format: int64
        - in: query
          name: isStage
          description: List all accounting scripts in production or staging environment
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/Page'
                  - properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/AccountingScriptV2'
        '400':
          description: Bad request
      deprecated: false
  /v2/accounting-scripts/{accountingScriptId}:
    get:
      tags:
        - Accounting scripts V2
      summary: Get accounting script V2
      operationId: getAccountingScriptByIdV2
      description: |
        Get a specific accounting script by its ID.
      parameters:
        - in: path
          name: accountingScriptId
          schema:
            type: integer
            format: int64
          required: true
          description: Accounting script ID
      responses:
        '200':
          description: Accounting script found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingScriptV2'
        '404':
          description: Not found
      deprecated: false
  /v1/accounting-scripts:
    post:
      operationId: CreateAccountingScript
      summary: Create accounting script V1
      description: >
        Create an accounting script. 


        Refer to the [How to create accounting
        script](doc:create-an-accounting-script) guide for more information.
      tags:
        - Accounting scripts V1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountingScriptPost'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingScript'
        '400':
          description: Bad request when a provided parameter is invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error description
                    example: Validation error, entry Type doesn't exists
        '409':
          description: Accounting script already exists
    get:
      operationId: SearchAccountingScript
      summary: List accounting scripts V1
      description: List existing accounting scripts for your organization.
      tags:
        - Accounting scripts V1
      parameters:
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/pageOffset'
        - in: query
          name: debitAccountingAccount
          description: List all accounting scripts related to a debit accounting account
          schema:
            type: string
        - in: query
          name: creditAccountingAccount
          description: List all accounting scripts related to a credit accounting account
          schema:
            type: string
        - in: query
          name: programId
          description: List all accounting scripts related to a program
          schema:
            type: integer
            format: int64
        - in: query
          name: eventTypeId
          description: List all accounting scripts related to an event type
          schema:
            type: integer
            format: int64
        - in: query
          name: entryTypeId
          description: List all accounting scripts related to an entry type
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/Page'
                  - properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/AccountingScript'
        '400':
          description: Bad request
      deprecated: false
  /v1/accounting-scripts/batch:
    patch:
      operationId: BatchUpdateAccountingScript
      summary: Update accounting scripts V1
      description: |
        Update accounting scripts.
      tags:
        - Accounting scripts V1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchAccountingScriptPatch'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingScriptPatchResponse'
              example:
                '393028':
                  has_error: false
                  new_id: 403948
        '400':
          description: Bad request - invalid parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingScriptPatchResponse'
              example:
                '393028':
                  has_error: true
                  error_message: Debit account not found
  /v1/buckets:
    get:
      operationId: GetBucketsByAccount
      summary: Get account buckets
      description: >
        Get one or all buckets for a specific tenant. Buckets are accumulators
        that are related to an accounting script. Buckets can have their values
        changed with each related accounting entry.
      tags:
        - Buckets
      parameters:
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/pageOffset'
        - in: query
          name: accountId
          schema:
            type: integer
          description: Account ID
        - in: query
          name: name
          schema:
            type: string
          required: false
          description: Bucket name
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/Page'
                  - properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/Bucket'
        '400':
          description: Bad request
  /v1/accounting-scripts/{accountingScriptId}:
    get:
      operationId: GetAccountingScriptById
      summary: Get accounting script V1
      description: Get a specific accounting script by its ID.
      tags:
        - Accounting scripts V1
      parameters:
        - in: path
          name: accountingScriptId
          schema:
            type: integer
            format: int64
          required: true
          description: Accounting script ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingScript'
        '404':
          description: Accounting script not found
      deprecated: false
    patch:
      operationId: UpdateAccountingScript
      summary: Update accounting script V1
      description: |
        Update accounting script.
      tags:
        - Accounting scripts V1
      parameters:
        - in: path
          name: accountingScriptId
          schema:
            type: integer
            format: int64
          required: true
          description: Accounting script ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountingScriptPatch'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingScriptSinglePatchResponse'
              example:
                new_id: 403948
        '400':
          description: Bad request - invalid parameter
          content:
            application/json:
              example:
                message: Debit account not found
    delete:
      operationId: DeactivateAccountingScript
      summary: Deactivate accounting script V1
      description: Deactivate an accounting script by its ID.
      tags:
        - Accounting scripts V1
      parameters:
        - in: path
          name: accountingScriptId
          schema:
            type: integer
            format: int64
          required: true
          description: Numeric ID of the accounting script.
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingScript'
        '404':
          description: Accounting script not found
  /v1/accounting-entries:
    post:
      operationId: CreateAccountingEntry
      summary: Create accounting entry
      description: >
        Create an accounting entry. 


        This endpoint generates an [Accounting entry
        created](https://developers.pismo.io/events/docs/accounting-entry-creation-1)
        event.


        Refer to the [How to create accounting
        entries](doc:create-accounting-entries) guide for more information.
      tags:
        - Accounting entry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountingEntryPost'
      responses:
        '202':
          description: Request accepted but not processed yet.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountingEntryPost'
        '400':
          description: Bad request when a provided parameter is invalid.
        '409':
          description: Conflict when TrackingId already exists.
