openapi: 3.1.0
info:
  title: Platform setup - Divisions
  description: >-
    Use administrative divisions to align organization territory with business
    needs
  version: v1.0
  contact:
    name: Pismo Support
    url: https://developers.pismo.io/support/
  license:
    name: Copyright Pismo
servers:
  - url: https://sandbox.pismolabs.io
    description: Sandbox API server for testing
security:
  - S2SAuthentication: []
tags:
  - name: Administrative divisions (deprecated)
    description: View and manage administrative divisions.
  - name: Administrative divisions V2 (deprecated)
    description: View and manage admin divisions for transaction banking
components:
  parameters:
    AdminDivisionIdPath:
      description: Administrative division ID.
      in: path
      name: id
      required: true
      schema:
        type: integer
    AdminDivisionExternalIdPath:
      description: Client-supplied external ID
      in: path
      name: id
      required: true
      schema:
        type: string
    DivisionCodePath:
      description: Division code that identifies division.
      in: path
      name: code
      required: true
      schema:
        type: string
    DivisionCodePath2:
      description: Division code that identifies division.
      in: path
      name: divisionCode
      required: true
      schema:
        type: string
    DivisionCodeQuery:
      in: query
      name: code
      description: >
        Division code filter. A division code is a client-generated ID for
        client monitoring and tracking.
      required: true
      schema:
        type: string
    DivisionIdQuery:
      in: query
      name: id
      description: Division ID filter
      required: false
      schema:
        type: string
    LimitQuery2:
      in: query
      name: limit
      description: >
        Number of results to return per page. Maximum and default is 100 or
        until 1MB is reached.
      required: false
      schema:
        type: string
    NextCursorQuery:
      name: nextCursor
      in: query
      description: >-
        Pagination cursor for the next page. This is the `next_curor` field in
        the response,
      required: false
      schema:
        type: string
    PageQuery:
      description: Page must be greater than `0`. Default = `1`.
      in: query
      name: page
      required: true
      schema:
        type: integer
    PerPageQuery:
      description: PerPage must be greater than `0`. Default = `10`.
      in: query
      name: perPage
      required: true
      schema:
        type: integer
  schemas:
    AdminDivisionExternalID:
      type: string
      description: >-
        Client-supplied external ID. It must comply with the rule
        `^[a-zA-Z0-9-]+$`.
      example: '8675309'
    AdminDivisionExternalIdReference:
      type: string
      description: External ID reference. Must comply with the rule `^[a-zA-Z0-9-]+$`.
      example: CRM-software-ID
    AdminDivisionID:
      type: integer
      description: Admininistrative division ID
      example: 84849
    AdminDivisionName:
      type: string
      description: Administrative division name
      example: Scotland
    AdminDivisionParentID:
      type: integer
      description: Parent ID
    AdminDivisionParentExternalID:
      type: string
      description: Parent external ID. Must comply with the rule `^[a-zA-Z0-9-]+$`.
      example: '8675309'
    AdminDivisionType:
      type: string
      description: Admin division type
      enum:
        - City
        - State
        - Country
      example: State
    CountryCode:
      type: string
      maxLength: 3
      description: ISO 3-letter country code.
      example: BRA
    CurrencyCode:
      type: string
      maxLength: 3
      description: ISO currency numeric code.
      example: '986'
    DivisionCode:
      type: string
      maxLength: 36
      description: >
        Division code ID. This field is client-generated for client monitoring
        and tracking.
      example: DIV-BR-SP-001
    DivisionCreatedAt:
      type: string
      format: date-time
      description: Division creation timestamp.
      example: '2025-05-22T17:45:13.717773Z'
    DivisionDescription:
      type: string
      maxLength: 80
      description: Division description.
      example: Division responsible for operations in the Hong Kong metropolitan area
    DivisionID:
      type: string
      description: Division unique ID
      example: b9a5cc7e-2052-402f-bf81-bbe3964f9f3f
    DivisionLanguage:
      type: string
      maxLength: 5
      description: Division language setting.
      enum:
        - pt-BR
        - en-US
      example: pt-BR
    DivisionName:
      type: string
      maxLength: 40
      description: Division name.
      example: São Paulo Regional Division
    DivisionTimezone:
      type: string
      maxLength: 60
      description: Division timezone in IANA format.
      example: America/Sao_Paulo
    DivisionUpdatedAt:
      type: string
      format: date-time
      description: Division last update timestamp.
      example: '2025-06-01T10:15:00.000000Z'
    CycleClosing:
      type: string
      pattern: ^([01]?[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$
      description: End of day time in HH:MM:SS format.
      example: '18:00:00'
    handler.HTTPError:
      description: Code and error message.
      type: object
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error message
    HasNext:
      type: boolean
      description: Is there a next page?
      example: true
    HolidayCalendarID:
      type: integer
      format: int64
      description: Holiday group identifier.
      example: 1
    ItemsCount:
      type: integer
      description: Number of items in the current page
      example: 2
    Metadata:
      type: object
      description: >
        A valid JSON schema as specified in
        [https://json-schema.org/specification.html](https://json-schema.org/specification.html).
        Used to register the rules that are used to authorize the transaction.


        This object uses
        [parameters](doc:posting-transactions-on-holidays#parameters) to specify
        business rules for holidays. For details, see [Posting Transactions on
        Holidays](doc:posting-transactions-on-holidays).


        **Note**: This field must not be used to send Personally Identifiable
        Information (PII), Payment Card Industry (PCI) data, or any
        sensitive/regulated information. Metadata fields are intended for
        operational, non-sensitive data only. For sensitive data, use the
        specific parameters designed for that purpose. For more information,
        refer to [Get started with Pismo
        APIs](ref:get-started-with-pismo-apis#metadata).
    NextCursor:
      type: string
      description: Cursor for the next page, if available
      example: eyJpZCI6IjEyMyJ9
    pagination.Pagination:
      type: object
      properties:
        pages:
          type: integer
          description: Total number of result pages.
          example: 1
        current_page:
          type: integer
          description: Current result page.
          example: 1
        per_page:
          type: integer
          description: Maximum results per page.
          example: 10
        total_items:
          type: integer
          description: Total number of result items.
          example: 1
        items:
          type: array
          items:
            $ref: '#/components/schemas/presenter.v1AdministrativeDivisionResponse'
    presenter.CreateDivision:
      type: object
      required:
        - code
        - name
        - timezone
        - country_code
        - currency_numeric_code
        - program_type
      properties:
        code:
          $ref: '#/components/schemas/DivisionCode'
        name:
          $ref: '#/components/schemas/DivisionName'
        timezone:
          $ref: '#/components/schemas/DivisionTimezone'
        country_code:
          $ref: '#/components/schemas/CountryCode'
        currency_numeric_code:
          $ref: '#/components/schemas/CurrencyCode'
        program_type:
          $ref: '#/components/schemas/ProgramTypeString'
        description:
          $ref: '#/components/schemas/DivisionDescription'
        cycle_closing:
          $ref: '#/components/schemas/CycleClosing'
        language:
          $ref: '#/components/schemas/DivisionLanguage'
        holiday_calendar_id:
          $ref: '#/components/schemas/HolidayCalendarID'
    presenter.DivisionDetails:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/DivisionID'
        code:
          $ref: '#/components/schemas/DivisionCode'
        name:
          $ref: '#/components/schemas/DivisionName'
        description:
          $ref: '#/components/schemas/DivisionDescription'
        timezone:
          $ref: '#/components/schemas/DivisionTimezone'
        language:
          $ref: '#/components/schemas/DivisionLanguage'
        country_code:
          $ref: '#/components/schemas/CountryCode'
        currency_numeric_code:
          $ref: '#/components/schemas/CurrencyCode'
        cycle_closing:
          $ref: '#/components/schemas/CycleClosing'
        program_type:
          $ref: '#/components/schemas/ProgramTypeObject'
        holiday_calendar_id:
          $ref: '#/components/schemas/HolidayCalendarID'
        created_at:
          $ref: '#/components/schemas/DivisionCreatedAt'
        updated_at:
          $ref: '#/components/schemas/DivisionUpdatedAt'
    presenter.DivisionDetailsPage:
      type: object
      properties:
        has_next:
          $ref: '#/components/schemas/HasNext'
        next_cursor:
          $ref: '#/components/schemas/NextCursor'
        count:
          $ref: '#/components/schemas/ItemsCount'
        items:
          type: array
          description: List of division details
          items:
            $ref: '#/components/schemas/presenter.DivisionDetails'
    presenter.PatchDivisionRequest:
      type: object
      properties:
        code:
          $ref: '#/components/schemas/DivisionCode'
        name:
          $ref: '#/components/schemas/DivisionName'
        description:
          $ref: '#/components/schemas/DivisionDescription'
        timezone:
          $ref: '#/components/schemas/DivisionTimezone'
        language:
          $ref: '#/components/schemas/DivisionLanguage'
        country_code:
          $ref: '#/components/schemas/CountryCode'
        currency_numeric_code:
          $ref: '#/components/schemas/CurrencyCode'
        cycle_closing:
          $ref: '#/components/schemas/CycleClosing'
        holiday_calendar_id:
          $ref: '#/components/schemas/HolidayCalendarID'
    presenter.v1AdministrativeDivisionResponse:
      type: object
      description: Administrative division data.
      properties:
        id:
          $ref: '#/components/schemas/AdminDivisionID'
        name:
          $ref: '#/components/schemas/AdminDivisionName'
        type:
          $ref: '#/components/schemas/AdminDivisionType'
        parent_id:
          $ref: '#/components/schemas/AdminDivisionParentID'
        external_id:
          $ref: '#/components/schemas/AdminDivisionExternalID'
    presenter.v1CreateAdministrativeDivisionRequest:
      type: object
      description: Data to create an administrative division
      required:
        - name
        - type
      properties:
        name:
          $ref: '#/components/schemas/AdminDivisionName'
        type:
          $ref: '#/components/schemas/AdminDivisionType'
        parent_id:
          $ref: '#/components/schemas/AdminDivisionParentID'
        external_id:
          $ref: '#/components/schemas/AdminDivisionExternalID'
        external_id_reference:
          $ref: '#/components/schemas/AdminDivisionExternalIdReference'
    presenter.v1CreateAdministrativeDivisionResponse:
      description: Administrative division creation response
      type: object
      properties:
        id:
          $ref: '#/components/schemas/AdminDivisionID'
        external_id:
          $ref: '#/components/schemas/AdminDivisionExternalID'
        name:
          $ref: '#/components/schemas/AdminDivisionName'
        parent_id:
          $ref: '#/components/schemas/AdminDivisionParentID'
        type:
          $ref: '#/components/schemas/AdminDivisionType'
    presenter.v1UpdateAdministrativeDivisionRequest:
      type: object
      description: Data to update an administrative division
      required:
        - name
        - type
      properties:
        name:
          $ref: '#/components/schemas/AdminDivisionName'
        type:
          $ref: '#/components/schemas/AdminDivisionType'
        parent_id:
          $ref: '#/components/schemas/AdminDivisionParentID'
        external_id:
          $ref: '#/components/schemas/AdminDivisionExternalID'
    presenter.v2AdministrativeDivisionResponse:
      description: Administrative division response
      type: object
      properties:
        id:
          $ref: '#/components/schemas/AdminDivisionID'
        external_id:
          $ref: '#/components/schemas/AdminDivisionExternalID'
        name:
          $ref: '#/components/schemas/AdminDivisionName'
        parent_id:
          $ref: '#/components/schemas/AdminDivisionParentID'
        type:
          $ref: '#/components/schemas/AdminDivisionType'
        working_days:
          $ref: '#/components/schemas/WorkingDays'
        metadata:
          $ref: '#/components/schemas/Metadata'
    presenter.v2CreateAdministrativeDivisionRequest:
      type: object
      description: Data to create an administrative division (transaction banking)
      required:
        - name
        - type
      properties:
        name:
          $ref: '#/components/schemas/AdminDivisionName'
        type:
          $ref: '#/components/schemas/AdminDivisionType'
        parent_id:
          $ref: '#/components/schemas/AdminDivisionParentID'
        external_id:
          $ref: '#/components/schemas/AdminDivisionExternalID'
        parent_external_id:
          $ref: '#/components/schemas/AdminDivisionParentExternalID'
        working_days:
          $ref: '#/components/schemas/WorkingDays'
        metadata:
          $ref: '#/components/schemas/Metadata'
    presenter.v2UpdateAdministrativeDivisionRequest:
      description: Data to update an administrative division (transaction banking)
      type: object
      properties:
        name:
          $ref: '#/components/schemas/AdminDivisionName'
        type:
          $ref: '#/components/schemas/AdminDivisionType'
        parent_id:
          $ref: '#/components/schemas/AdminDivisionParentID'
        external_id:
          $ref: '#/components/schemas/AdminDivisionExternalID'
        working_days:
          $ref: '#/components/schemas/WorkingDays'
        metadata:
          $ref: '#/components/schemas/Metadata'
    ProgramTypeObject:
      type: object
      properties:
        id:
          type: integer
          description: Program type ID
          example: 1
        description:
          type: string
          description: Program type description.
          example: Full balance credit progra,m
    ProgramTypeString:
      type: string
      description: >
        Program type:
          `CREDITO` — Full balance credit accounts<br>
          `PRE-PAGO` — Full balance prepaid accounts<br>
          `DEBITO` — Full balance debit accounts<br>
          `MERCHANT` — Merchant accounts<br>
          `CREDITO ZERO-BALANCE` — Zero balance credit accounts<br>
          `PRE-PAGO ZERO-BALANCE` — Zero balance prepaid accounts<br>
          `DEBITO ZERO-BALANCE` — Zero balance debit accounts<br>
          `CURRENT ACCOUNTS` — Current accounts<br>
          `INTERNAL ACCOUNTS` — Internal accounts<br>
          `CORRESPONDENT ACCOUNTS` — Correspondent accounts<br>
          `VOUCHER` - Prepaid voucher meal/food card<br>

        For more information, refer to [Program
        types](https://developers.pismo.io/pismo-docs/docs/program-types)
      enum:
        - CREDITO
        - PRE-PAGO
        - DEBITO
        - MERCHANT
        - CREDITO ZERO-BALANCE
        - PRE-PAGO ZERO-BALANCE
        - DEBITO ZERO-BALANCE
        - CURRENT ACCOUNTS
        - INTERNAL ACCOUNTS
        - CORRESPONDENT ACCOUNTS
        - VOUCHER
      example: CREDITO
    WorkingDays:
      type: array
      description: >
        Week days that are working days where `0` = Sunday and `6` = Saturday.
        The default - [1,2,3,4,5] - corresponds to Monday through Friday.
      items:
        type: integer
      example:
        - 1
        - 2
        - 3
        - 4
        - 5
  responses:
    400InvalidRequest:
      description: Invalid request or validation error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/handler.HTTPError'
    401UnauthorizedError:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/handler.HTTPError'
    404DivisionNotFound:
      description: Division not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/handler.HTTPError'
    409DivisionAlreadyExists:
      description: Division code already exists
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/handler.HTTPError'
    500InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/handler.HTTPError'
  securitySchemes:
    S2SAuthentication:
      type: http
      scheme: bearer
      description: All requests must be previously authenticated with an account token.
  examples:
    MissingTenantResponse:
      value:
        code: '400'
        message: Missing x-tenant header
    InvalidParamsResponse:
      value:
        code: '400'
        message: Invalid {parameter_name} parameter value
    HierarchyLoopResponse:
      value:
        code: '400'
        message: >-
          The parent_id {parent_id} causes a circular hierarchy loop with the
          administrative_division id {id}.
    InternalServerErrorResponse:
      value:
        code: '500'
        message: >-
          The parent_id {parent_id} causes a circular hierarchy loop with the
          administrative_division id {id}.
    NotFoundResponse:
      value:
        code: '404'
        message: '{target_name} not found'
    ConflictResponse:
      value:
        code: '409'
        message: '{target_name} already exists'
    GetV1AdministrativeDivisionResponse:
      value:
        id: 1
        name: Brazil
        type: Country
        parent_id: 0
        external_id: BR
    GetV2AdministrativeDivisionResponse:
      value:
        id: 1
        name: Brazil
        type: Country
        external_id: BR
        working_days:
          - 1
          - 2
          - 3
          - 4
          - 5
        metadata:
          accrue_interest: true
          check_dormancy: true
          create_account: false
          defer_statement_due_date: true
          defer_transactions: true
          post_interest: false
          post_transactions: false
          run_cycle_closing: false
    GetPaginatedListOfAdministrativeDivisionsTree:
      value:
        pages: 1
        current_page: 1
        per_page: 10
        total_items: 3
        items:
          - id: 43
            name: Brazil
            type: Country
            parent_id: 41
            external_id: BR
          - id: 44
            name: Minas Gerais
            type: State
            parent_id: 43
            external_id: MG
          - id: 45
            name: Rio de Janeiro
            type: State
            parent_id: 43
            external_id: RJ
          - id: 4533
            name: Itaboraí
            type: City
            parent_id: 45
            external_id: RJ-Itaboraí
    GetPaginatedListOfAdministrativeDivisionsAncestors:
      value:
        pages: 1
        current_page: 1
        per_page: 10
        total_items: 3
        items:
          - id: 5222005
            name: Vianópolis
            type: City
            parent_id: 1052
            external_id: GO-Vianópolis
          - id: 1052
            name: Goiás
            type: State
            parent_id: 1001
            external_id: GO
          - id: 1001
            name: Brasil
            type: Country
            external_id: BR
    GetPaginatedListOfAdministrativeDivisionsTreeWithMetadata:
      value:
        pages: 1
        current_page: 1
        per_page: 10
        total_items: 3
        items:
          - id: 43
            name: Brazil
            type: Country
            external_id: BR
            working_days:
              - 1
              - 2
              - 3
              - 4
              - 5
            metadata:
              accrue_interest: true
              check_dormancy: true
              create_account: false
              defer_statement_due_date: true
              defer_transactions: true
              post_interest: false
              post_transactions: false
              run_cycle_closing: false
          - id: 44
            name: Minas Gerais
            type: State
            parent_id: 43
            external_id: MG
            working_days:
              - 1
              - 2
              - 3
              - 4
              - 5
            metadata:
              accrue_interest: true
              check_dormancy: true
              create_account: false
              defer_statement_due_date: true
              defer_transactions: true
              post_interest: false
              post_transactions: false
              run_cycle_closing: false
          - id: 45
            name: Rio de Janeiro
            type: State
            parent_id: 43
            external_id: RJ
            working_days:
              - 1
              - 2
              - 3
              - 4
              - 5
            metadata:
              accrue_interest: true
              check_dormancy: true
              create_account: false
              defer_statement_due_date: true
              defer_transactions: true
              post_interest: false
              post_transactions: false
              run_cycle_closing: false
          - id: 4533
            name: Itaboraí
            type: City
            parent_id: 45
            external_id: RJ-Itaboraí
            working_days:
              - 1
              - 2
              - 3
              - 4
              - 5
            metadata:
              accrue_interest: true
              check_dormancy: true
              create_account: false
              defer_statement_due_date: true
              defer_transactions: true
              post_interest: false
              post_transactions: false
              run_cycle_closing: false
    GetPaginatedListOfAdministrativeDivisionsAncestorsWithMetadata:
      value:
        pages: 1
        current_page: 1
        per_page: 10
        total_items: 3
        items:
          - id: 5222005
            name: Vianópolis
            type: City
            parent_id: 1052
            external_id: GO-Vianópolis
            working_days:
              - 1
              - 2
              - 3
              - 4
              - 5
            metadata:
              accrue_interest: true
              check_dormancy: true
              create_account: false
              defer_statement_due_date: true
              defer_transactions: true
              post_interest: false
              post_transactions: false
              run_cycle_closing: false
          - id: 1052
            name: Goiás
            type: State
            parent_id: 1001
            external_id: GO
            working_days:
              - 1
              - 2
              - 3
              - 4
              - 5
            metadata:
              accrue_interest: true
              check_dormancy: true
              create_account: false
              defer_statement_due_date: true
              defer_transactions: true
              post_interest: false
              post_transactions: false
              run_cycle_closing: false
          - id: 1001
            name: Brasil
            type: Country
            external_id: BR
            working_days:
              - 1
              - 2
              - 3
              - 4
              - 5
            metadata:
              accrue_interest: true
              check_dormancy: true
              create_account: false
              defer_statement_due_date: true
              defer_transactions: true
              post_interest: false
              post_transactions: false
              run_cycle_closing: false
    DivisionDetails:
      value:
        id: b9a5cc7e-2052-402f-bf81-bbe3964f9f3f
        code: DIV-BR-SP-001
        name: São Paulo Regional Division
        description: Division responsible for operations in the São Paulo metropolitan area
        timezone: America/Sao_Paulo
        language: pt-BR
        country_code: BRA
        currency_numeric_code: '986'
        cycle_closing: '18:00:00'
        program_type:
          id: 1
          description: CREDITO
        holiday_calendar_id: 1
        created_at: '2025-05-22T17:45:13.717773Z'
    DivisionDetailsPage:
      value:
        has_next: true
        next_cursor: eyJpZCI6IjEyMyJ9
        count: 2
        items:
          - id: b9a5cc7e-2052-402f-bf81-bbe3964f9f3f
            code: DIV-BR-SP-001
            name: São Paulo Regional Division
            description: >-
              Division responsible for operations in the São Paulo metropolitan
              area
            timezone: America/Sao_Paulo
            language: pt-BR
            country_code: BRA
            currency_numeric_code: '986'
            cycle_closing: '18:00:00'
            program_type:
              id: 1
              description: CREDITO
            holiday_calendar_id: 1
            created_at: '2025-05-22T17:45:13.717773Z'
            updated_at: '2025-06-01T10:15:00.000000Z'
          - id: c1b2cc7e-2052-402f-bf81-bbe3964f9f3f
            code: DIV-BR-RJ-002
            name: Rio de Janeiro Regional Division
            description: >-
              Division responsible for operations in the Rio de Janeiro
              metropolitan area
            timezone: America/Sao_Paulo
            language: en-US
            country_code: BRA
            currency_numeric_code: '986'
            cycle_closing: '19:00:00'
            program_type:
              id: 1
              description: CREDITO
            holiday_calendar_id: 2
            created_at: '2025-05-23T10:00:00.000000Z'
paths:
  /divisions-core/v1/administrative-division:
    post:
      summary: Create administrative division (deprecated)
      description: >
        **DEPRECATED**. Call [Create holiday
        calendar](ref:post-create-holiday-calendar) instead. 


        This endpoint is deprecated starting April 30, 2026, and final removal
        from both test (EXT) and production environments on October 30, 2026.


        Create an administrative division. 


        Administrative divisions are used to divide an organization's territory
        into separate areas. An organization covering Great Britian for example,
        might want to have separate divisions for England, Scotland, and
        Ireland. Each of these countries may have different holidays and need to
        be administered in different ways. 


        There is a [Create administrative division](ref:post-v2-admin-division)
        V2 endpoint designed for greater flexibility in defining non-business
        days to accommodate specific business requirements. For details about
        the differences, refer to [Platform setup - Holidays and administrative
        divisions](doc:platform-setup-holidays#endpoints-for-transaction-banking).
      operationId: post-v1-admin-division
      deprecated: true
      tags:
        - Administrative divisions (deprecated)
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/presenter.v1CreateAdministrativeDivisionRequest
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/presenter.v1CreateAdministrativeDivisionResponse
        '400':
          description: Bad request error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                response-missing-tenant:
                  $ref: '#/components/examples/MissingTenantResponse'
                invalid-params-response:
                  $ref: '#/components/examples/InvalidParamsResponse'
        '401':
          $ref: '#/components/responses/401UnauthorizedError'
        '404':
          description: Not found error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                not-found-response:
                  $ref: '#/components/examples/NotFoundResponse'
        '500':
          $ref: '#/components/responses/500InternalServerError'
  /divisions-core/v1/administrative-division/external-id/{id}:
    get:
      summary: Get admin division info by external ID (deprecated)
      description: >
        **DEPRECATED**. Call [Get calendar by external
        ID](ref:get-holiday-calendar-by-external-id) instead. 


        This endpoint is deprecated starting April 30, 2026, and final removal
        from both test (EXT) and production environments on October 30, 2026.


        Get detailed administrative division information.
      operationId: get-v1-admin-division-external-id
      deprecated: true
      tags:
        - Administrative divisions (deprecated)
      parameters:
        - description: Administrative division external ID
          in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Administrative division details
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/presenter.v1AdministrativeDivisionResponse
              examples:
                response-v1-administrative-division:
                  $ref: '#/components/examples/GetV1AdministrativeDivisionResponse'
        '400':
          description: Bad request error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                response-missing-tenant:
                  $ref: '#/components/examples/MissingTenantResponse'
                invalid-params-response:
                  $ref: '#/components/examples/InvalidParamsResponse'
        '401':
          $ref: '#/components/responses/401UnauthorizedError'
        '404':
          description: Not found error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                not-found-response:
                  $ref: '#/components/examples/NotFoundResponse'
        '500':
          $ref: '#/components/responses/500InternalServerError'
  /divisions-core/v1/administrative-division/{id}:
    get:
      summary: Get admin division info (deprecated)
      description: >

        **DEPRECATED**. Call [Get holiday calendar](ref:get-holiday-calendar)
        instead. 

         This endpoint is deprecated starting April 30, 2026, and final removal from both test (EXT) and production environments on October 30, 2026.

         Get detailed administrative division information.
      operationId: get-v1-admin-division
      deprecated: true
      tags:
        - Administrative divisions (deprecated)
      parameters:
        - $ref: '#/components/parameters/AdminDivisionIdPath'
      responses:
        '200':
          description: Administrative division details.
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/presenter.v1AdministrativeDivisionResponse
              examples:
                response-v1-administrative-division:
                  $ref: '#/components/examples/GetV1AdministrativeDivisionResponse'
        '400':
          description: Bad request error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                response-missing-tenant:
                  $ref: '#/components/examples/MissingTenantResponse'
                invalid-params-response:
                  $ref: '#/components/examples/InvalidParamsResponse'
        '401':
          $ref: '#/components/responses/401UnauthorizedError'
        '404':
          description: Not found error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                not-found-response:
                  $ref: '#/components/examples/NotFoundResponse'
        '500':
          $ref: '#/components/responses/500InternalServerError'
    put:
      summary: Update administrative division (deprecated)
      description: >
        **DEPRECATED**. Call [Update holiday
        calendar](ref:update-holiday-calendar) instead. 


        This endpoint is deprecated starting April 30, 2026, and final removal
        from both test (EXT) and production environments on October 30, 2026.


        Update administrative division.
      tags:
        - Administrative divisions (deprecated)
      operationId: put-v1-admin-division
      deprecated: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/presenter.v1UpdateAdministrativeDivisionRequest
      parameters:
        - $ref: '#/components/parameters/AdminDivisionIdPath'
      responses:
        '200':
          description: Updated.
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/presenter.v1AdministrativeDivisionResponse
              examples:
                response-v1-administrative-division:
                  $ref: '#/components/examples/GetV1AdministrativeDivisionResponse'
        '400':
          description: Bad request error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                response-missing-tenant:
                  $ref: '#/components/examples/MissingTenantResponse'
                invalid-params-response:
                  $ref: '#/components/examples/InvalidParamsResponse'
        '401':
          $ref: '#/components/responses/401UnauthorizedError'
        '404':
          description: Not found error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                not-found-response:
                  $ref: '#/components/examples/NotFoundResponse'
        '500':
          $ref: '#/components/responses/500InternalServerError'
    delete:
      tags:
        - Administrative divisions (deprecated)
      operationId: delete-v1-admin-division
      deprecated: true
      summary: Delete administrative division (deprecated)
      description: >
        **DEPRECATED**. Call [Delete holiday
        calendar](ref:delete-holiday-calendar) instead. 


        This endpoint is deprecated starting April 30, 2026, and final removal
        from both test (EXT) and production environments on October 30, 2026.


        Delete an administrative division.
      parameters:
        - $ref: '#/components/parameters/AdminDivisionIdPath'
      responses:
        '204':
          description: No Content.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                response-missing-tenant:
                  $ref: '#/components/examples/MissingTenantResponse'
                invalid-params-response:
                  $ref: '#/components/examples/InvalidParamsResponse'
        '401':
          $ref: '#/components/responses/401UnauthorizedError'
        '404':
          description: Not found error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                response-missing-tenant:
                  $ref: '#/components/examples/NotFoundResponse'
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                generic-internal-error:
                  $ref: '#/components/examples/InternalServerErrorResponse'
  /divisions-core/v1/administrative-division/{id}/tree:
    get:
      summary: Get admin division tree by admin division ID (deprecated)
      description: >
        **DEPRECATED**. Call [List holiday
        calendars](ref:list-holiday-calendars) instead. 


        This endpoint is deprecated starting April 30, 2026, and final removal
        from both test (EXT) and production environments on October 30, 2026.


        Get the complete tree of child administrative divisions using the
        parent's administrative division ID.
      tags:
        - Administrative divisions (deprecated)
      operationId: get-v1-admin-division-tree-parent-id
      deprecated: true
      parameters:
        - $ref: '#/components/parameters/AdminDivisionExternalIdPath'
        - $ref: '#/components/parameters/PageQuery'
        - $ref: '#/components/parameters/PerPageQuery'
      responses:
        '200':
          description: Paginated list of administrative divisions.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pagination.Pagination'
              examples:
                PaginatedListOfAdministrativeDivisionsTree:
                  $ref: >-
                    #/components/examples/GetPaginatedListOfAdministrativeDivisionsTree
                PaginatedListOfAdministrativeDivisionsTreeWithMetadata:
                  $ref: >-
                    #/components/examples/GetPaginatedListOfAdministrativeDivisionsTreeWithMetadata
        '400':
          description: Bad request error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                response-missing-tenant:
                  $ref: '#/components/examples/MissingTenantResponse'
                invalid-params-response:
                  $ref: '#/components/examples/InvalidParamsResponse'
        '401':
          $ref: '#/components/responses/401UnauthorizedError'
        '500':
          $ref: '#/components/responses/500InternalServerError'
  /divisions-core/v1/administrative-division/external-id/{id}/tree:
    get:
      summary: Get admin division tree by external ID (deprecated)
      description: >
        **DEPRECATED**. Call [List holiday
        calendars](ref:list-holiday-calendars) instead. 


        This endpoint is deprecated starting April 30, 2026, and final removal
        from both test (EXT) and production environments on October 30, 2026.


        Get the full tree of administrative divisions using an external ID
      operationId: get-v1-admin-division-tree-external-id
      deprecated: true
      tags:
        - Administrative divisions (deprecated)
      parameters:
        - $ref: '#/components/parameters/AdminDivisionExternalIdPath'
        - $ref: '#/components/parameters/PageQuery'
        - $ref: '#/components/parameters/PerPageQuery'
      responses:
        '200':
          description: Paginated list of administrative divisions.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pagination.Pagination'
              examples:
                PaginatedListOfAdministrativeDivisionsTree:
                  $ref: >-
                    #/components/examples/GetPaginatedListOfAdministrativeDivisionsTree
                PaginatedListOfAdministrativeDivisionsTreeWithMetadata:
                  $ref: >-
                    #/components/examples/GetPaginatedListOfAdministrativeDivisionsTreeWithMetadata
        '400':
          description: Bad request error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                response-missing-tenant:
                  $ref: '#/components/examples/MissingTenantResponse'
                invalid-params-response:
                  $ref: '#/components/examples/InvalidParamsResponse'
        '401':
          $ref: '#/components/responses/401UnauthorizedError'
        '500':
          $ref: '#/components/responses/500InternalServerError'
  /divisions-core/v1/administrative-division/{id}/ancestors:
    get:
      summary: Get admin division ancestors by admin division ID (deprecated)
      description: >
        **DEPRECATED**. Call [List holiday
        calendars](ref:list-holiday-calendars) instead. 


        This endpoint is deprecated starting April 30, 2026, and final removal
        from both test (EXT) and production environments on October 30, 2026.


        List ancestors for an administrative division using administrative
        division ID.
      operationId: get-v1-admin-division-ancestors-administrative-division-id
      deprecated: true
      tags:
        - Administrative divisions (deprecated)
      parameters:
        - $ref: '#/components/parameters/AdminDivisionIdPath'
        - $ref: '#/components/parameters/PageQuery'
        - $ref: '#/components/parameters/PerPageQuery'
      responses:
        '200':
          description: Paginated list of administrative divisions.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pagination.Pagination'
              examples:
                PaginatedListOfAdministrativeDivisionsTree:
                  $ref: >-
                    #/components/examples/GetPaginatedListOfAdministrativeDivisionsAncestors
                PaginatedListOfAdministrativeDivisionsTreeWithMetadata:
                  $ref: >-
                    #/components/examples/GetPaginatedListOfAdministrativeDivisionsAncestorsWithMetadata
        '400':
          description: Bad request error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                response-missing-tenant:
                  $ref: '#/components/examples/MissingTenantResponse'
                invalid-params-response:
                  $ref: '#/components/examples/InvalidParamsResponse'
        '401':
          $ref: '#/components/responses/401UnauthorizedError'
        '500':
          $ref: '#/components/responses/500InternalServerError'
  /divisions-core/v1/administrative-division/external-id/{id}/ancestors:
    get:
      summary: Get admin division ancestors by external ID (deprecated)
      description: >
        **DEPRECATED**. Call [List holiday
        calendars](ref:list-holiday-calendars) instead. 


        This endpoint is deprecated starting April 30, 2026, and final removal
        from both test (EXT) and production environments on October 30, 2026.


        List ancestors for an administrative division using an external ID.
      operationId: get-v1-admin-division-ancestors-external-id
      deprecated: true
      tags:
        - Administrative divisions (deprecated)
      parameters:
        - $ref: '#/components/parameters/AdminDivisionExternalIdPath'
        - $ref: '#/components/parameters/PageQuery'
        - $ref: '#/components/parameters/PerPageQuery'
      responses:
        '200':
          description: Paginated list of administrative divisions.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pagination.Pagination'
              examples:
                PaginatedListOfAdministrativeDivisionsTree:
                  $ref: >-
                    #/components/examples/GetPaginatedListOfAdministrativeDivisionsAncestors
                PaginatedListOfAdministrativeDivisionsTreeWithMetadata:
                  $ref: >-
                    #/components/examples/GetPaginatedListOfAdministrativeDivisionsAncestorsWithMetadata
        '400':
          description: Bad request error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                response-missing-tenant:
                  $ref: '#/components/examples/MissingTenantResponse'
                invalid-params-response:
                  $ref: '#/components/examples/InvalidParamsResponse'
        '401':
          $ref: '#/components/responses/401UnauthorizedError'
        '500':
          $ref: '#/components/responses/500InternalServerError'
  /divisions-core/v2/administrative-division:
    post:
      summary: Create administrative division (deprecated)
      description: >
        **DEPRECATED**. Call [Create holiday
        calendar](ref:post-create-holiday-calendar) instead. 


        This endpoint is deprecated starting April 30, 2026, and final removal
        from both test (EXT) and production environments on October 30, 2026.


        Create an administrative division. 


        This is a v2 endpoint that offers more granular control over financial
        activities on non-business days. To understand the differences between
        v1 and v2 endpoints, refer to [Platform setup - Holidays and
        administrative
        divisions](doc:platform-setup-holidays#endpoints-for-transaction-banking).
      operationId: post-v2-admin-division
      deprecated: true
      tags:
        - Administrative divisions V2 (deprecated)
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/presenter.v2CreateAdministrativeDivisionRequest
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/presenter.v2AdministrativeDivisionResponse
        '400':
          description: Bad request error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                response-missing-tenant:
                  $ref: '#/components/examples/MissingTenantResponse'
                invalid-params-response:
                  $ref: '#/components/examples/InvalidParamsResponse'
        '401':
          $ref: '#/components/responses/401UnauthorizedError'
        '404':
          description: Not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                not-found-response:
                  $ref: '#/components/examples/NotFoundResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/responses/500InternalServerError'
  /divisions-core/v2/administrative-division/{id}:
    get:
      summary: Get administrative division info (deprecated)
      description: >
        **DEPRECATED**. Call [Get holiday calendar](ref:get-holiday-calendar)
        instead. 


        This endpoint is deprecated starting April 30, 2026, and final removal
        from both test (EXT) and production environments on October 30, 2026.


        Get administrative division detailed information.
      operationId: get-v2-admin-division
      deprecated: true
      tags:
        - Administrative divisions V2 (deprecated)
      parameters:
        - $ref: '#/components/parameters/AdminDivisionIdPath'
      responses:
        '200':
          description: Administrative division details.
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/presenter.v2AdministrativeDivisionResponse
              examples:
                response-v1-administrative-division:
                  $ref: '#/components/examples/GetV2AdministrativeDivisionResponse'
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                response-missing-tenant:
                  $ref: '#/components/examples/MissingTenantResponse'
                invalid-params-response:
                  $ref: '#/components/examples/InvalidParamsResponse'
        '401':
          $ref: '#/components/responses/401UnauthorizedError'
        '404':
          description: Not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                not-found-response:
                  $ref: '#/components/examples/NotFoundResponse'
        '500':
          $ref: '#/components/responses/500InternalServerError'
    put:
      summary: Update administrative division (deprecated)
      description: >
        **DEPRECATED**. Call [Update holiday
        calendar](ref:update-holiday-calendar) instead. 


        This endpoint is deprecated starting April 30, 2026, and final removal
        from both test (EXT) and production environments on October 30, 2026.


        Update an administrative division.
      operationId: put-v2-admin-division
      deprecated: true
      tags:
        - Administrative divisions V2 (deprecated)
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/presenter.v2UpdateAdministrativeDivisionRequest
      parameters:
        - description: Administrative division ID.
          in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/presenter.v2AdministrativeDivisionResponse
        '400':
          description: Bad request error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                response-missing-tenant:
                  $ref: '#/components/examples/MissingTenantResponse'
                invalid-params-response:
                  $ref: '#/components/examples/InvalidParamsResponse'
                hierarchyLoopResponse:
                  $ref: '#/components/examples/HierarchyLoopResponse'
        '401':
          $ref: '#/components/responses/401UnauthorizedError'
        '404':
          description: Not found error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handler.HTTPError'
              examples:
                not-found-response:
                  $ref: '#/components/examples/NotFoundResponse'
        '500':
          $ref: '#/components/responses/500InternalServerError'
